# Data Pipeline Demo

Data Source : https://data.jakarta.go.id/dataset/indeks-standar-pencemaran-udara-ispu-tahun-2021

In [246]:
from tqdm import tqdm
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np 
import joblib
import os
import yaml

In [164]:
params_dir = "../config/params.yaml"

In [165]:
def load_params(param_dir):
    with open(param_dir, 'r') as file:
        params = yaml.safe_load(file)
        
    return params

In [248]:
params = load_params(params_dir)

## 1. Data Collection

In [3]:
# fungsi untuk membaca nama file, memuat file, dan menggabungkan dataset
def read_dataset(dataset_dir):
    dataset = pd.DataFrame()

    for i in tqdm(os.listdir(dataset_dir)):
        dataset = pd.concat([pd.read_csv(dataset_dir + i), dataset])
    
    return dataset

In [4]:
# melakukan pembacaan nama file, memuat file, dan menggabungkan dataset
dataset = read_dataset(params["dataset_dir"])

100%|██████████| 7/7 [00:00<00:00, 174.98it/s]

In [5]:
# cek kondisi dataset
dataset

,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,categori,location
0,2021-09-01,DKI1 (Bunderan HI),63,88,29,15,24,38,88,PM25,SEDANG,NaN
1,2021-09-02,DKI1 (Bunderan HI),60,83,29,11,30,28,83,PM25,SEDANG,NaN
2,2021-09-03,DKI1 (Bunderan HI),60,82,27,11,37,30,82,PM25,SEDANG,NaN
3,2021-09-04,DKI1 (Bunderan HI),58,77,26,10,31,28,77,PM25,SEDANG,NaN
4,2021-09-05,DKI1 (Bunderan HI),63,85,27,11,28,28,85,PM25,SEDANG,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
150,2021-08-27,DKI5 (Kebon Jeruk) Jakarta Barat,61,96,34,8,29,15,96,PM25,SEDANG,NaN
151,2021-08-28,DKI5 (Kebon Jeruk) Jakarta Barat,63,100,31,8,44,12,100,PM25,SEDANG,NaN
152,2021-08-29,DKI5 (Kebon Jeruk) Jakarta Barat,67,111,32,10,36,13,111,PM25,TIDAK SEHAT,NaN
153,2021-08-30,DKI5 (Kebon Jeruk) Jakarta Barat,83,126,35,16,32,29,126,PM25,TIDAK SEHAT,NaN
154,2021-08-31,DKI5 (Kebon Jeruk) Jakarta Barat,60,92,30,7,32,14,92,PM25,SEDANG,NaN

In [6]:
# terdapat beberapa temuan disini:
# 1. index hanya terlihat sampai 154 padahal jumlah rows sampai 1070
# 2. tanggal hanya terlihat dari bulan 8 dan bulan 9
# 3. kolom location terlihat banyak NaN

# harus diselidiki lebih lanjut

In [7]:
# simpan dataset yang telah digabungkan
joblib.dump(dataset, "../data/processed/dataset.pkl")

['../data/processed/dataset.pkl']

## 2. Data Definition

In [8]:
# definisikan data

tanggal         :
    [datetime]
    [00:00 01/06/2021 - 23:59 31/12/2021]
    waktu saat pengambilan sampel

stasiun         :
    [object]
    ['DKI1 (Bunderan HI)', 'DKI2 (Kelapa Gading)', 'DKI3 (Jagakarsa)', 'DKI4 (Lubang Buaya)', 'DKI5 (Kebon Jeruk) Jakarta Barat']
    lokasi saat pengambilan sampel

pm10            :
    [integer]
    [0 - 800]
    partikel udara yang berukuran lebih kecil dari 10 mikron

pm25            :
    [integer]
    [0 - 400]
    partikel udara yang berukuran lebih kecil dari 2.5 mikron

so2             :
    [integer]
    [0 - 500]
    sulfur dioksida

co              :
    [integer]
    [0 - 100]
    karbon monoksida

o3              :
    [integer]
    [0 - 140]
    ozone

no2             :
    [integer]
    [0 - 100]
    nitrogen dioksida

max             :
    [integer]
    [0 - 800]
    nilai paling besar diantara pm10, pm25, so2, co, o3, dan no2

critical        :
    [object]
    [PM10, PM25, SO2, CO, O3, dan NO2]
    nama kolom untuk nilai max

categori        :
    [object]
    [BAIK, SEDANG, TIDAK SEHAT]
    kategori untuk data pengukuran udara

location        : tidak termasuk karena ada data yang nama kolomnya tidak standar

## 3. Data Validation

### 3.1. Tipe Data

In [9]:
# cek tipe data
dataset.dtypes

tanggal     object
stasiun     object
pm10        object
pm25        object
so2         object
co          object
o3          object
no2         object
max         object
critical    object
categori    object
location    object
dtype: object

In [10]:
# dari pengecekan data terlihat bahwa semuanya adalah data objek (string), perlu diselidiki lebih lanjut

### 3.2. Range

In [11]:
# pengecekan cakupan data menjadi kacau jika tipe data tidak sesuai
dataset.describe()

,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,categori,location
count,1070,765,1070,1070,1070,1070,1070,1070,1070,1062,1068,305
unique,214,5,112,180,175,76,108,100,206,96,8,4
top,2021-09-01,DKI1 (Bunderan HI),DKI2 (Kelapa Gading),71,---,10,13,15,77,PM25,SEDANG,SEDANG
freq,5,153,61,27,104,65,44,43,20,714,609,182

### 3.3. Dimensi Data

In [12]:
# dimensi data kemungkinan besar tidak terpengaruh, namun nanti kita kembali lagi
dataset.shape

(1070, 12)

### 3.4. Handling Columns Error

#### 3.4.1. Memperbaiki dataset yang kolomnya error

In [13]:
# dengan melihat file dataset satu persatu, terdapat 2 file yang nama kolomnya kemungkinan besar tidak benar
dataset_juli = pd.read_csv("../data/raw/indeks-standar-pencemar-udara-di-spku-bulan-juli-tahun-2021.csv")
dataset_juni = pd.read_csv("../data/raw/indeks-standar-pencemar-udara-di-spku-bulan-juni-tahun-2021.csv")

In [14]:
# cek dataset yang kolomnya bermasalah
dataset_juli

,tanggal,pm10,pm25,so2,co,o3,no2,max,critical,categori,location
0,2021-07-01,DKI1 (Bunderan HI),55,76,27,14,20,31,76,PM25,SEDANG
1,2021-07-02,DKI1 (Bunderan HI),55,70,33,16,14,30,70,PM25,SEDANG
2,2021-07-03,DKI1 (Bunderan HI),58,81,33,12,19,25,81,PM25,SEDANG
3,2021-07-04,DKI1 (Bunderan HI),68,102,27,11,27,22,102,PM25,TIDAK SEHAT
4,2021-07-05,DKI1 (Bunderan HI),71,106,28,12,34,25,106,PM25,TIDAK SEHAT
...,...,...,...,...,...,...,...,...,...,...,...
150,2021-07-27,DKI5 (Kebon Jeruk) Jakarta Barat,64,110,32,13,29,35,110,PM25,TIDAK SEHAT
151,2021-07-28,DKI5 (Kebon Jeruk) Jakarta Barat,70,130,33,17,28,45,130,PM25,TIDAK SEHAT
152,2021-07-29,DKI5 (Kebon Jeruk) Jakarta Barat,78,140,32,18,29,39,140,PM25,TIDAK SEHAT
153,2021-07-30,DKI5 (Kebon Jeruk) Jakarta Barat,75,121,37,12,50,21,121,PM25,TIDAK SEHAT
154,2021-07-31,DKI5 (Kebon Jeruk) Jakarta Barat,53,80,29,6,34,13,80,PM25,SEDANG

In [15]:
# cek dataset yang kolomnya bermasalah
dataset_juni

,tanggal,pm10,pm25,so2,co,o3,no2,max,critical,categori,location
0,2021-06-01,DKI1 (Bunderan HI),59,83,22,18,19,35,83,PM25,SEDANG
1,2021-06-02,DKI1 (Bunderan HI),59,84,21,20,24,38,84,PM25,SEDANG
2,2021-06-03,DKI1 (Bunderan HI),54,76,22,20,17,41,76,PM25,SEDANG
3,2021-06-04,DKI1 (Bunderan HI),63,87,20,13,14,30,87,PM25,SEDANG
4,2021-06-05,DKI1 (Bunderan HI),59,79,23,20,19,38,79,PM25,SEDANG
...,...,...,...,...,...,...,...,...,...,...,...
145,2021-06-26,DKI5 (Kebon Jeruk) Jakarta Barat,45,70,39,8,16,22,70,PM25,SEDANG
146,2021-06-27,DKI5 (Kebon Jeruk) Jakarta Barat,68,120,28,22,17,41,120,PM25,TIDAK SEHAT
147,2021-06-28,DKI5 (Kebon Jeruk) Jakarta Barat,59,99,25,17,21,30,99,PM25,SEDANG
148,2021-06-29,DKI5 (Kebon Jeruk) Jakarta Barat,72,128,35,24,21,50,128,PM25,TIDAK SEHAT
149,2021-06-30,DKI5 (Kebon Jeruk) Jakarta Barat,64,106,28,16,14,33,106,PM25,TIDAK SEHAT

In [16]:
# buat kolom baru yang urutannya sesuai dengan tipe datanya
dataset_new_columns = dataset_juni.columns.to_list()
dataset_new_columns.remove("location")
dataset_new_columns.insert(1, "stasiun")
dataset_new_columns

['tanggal',
 'stasiun',
 'pm10',
 'pm25',
 'so2',
 'co',
 'o3',
 'no2',
 'max',
 'critical',
 'categori']

In [17]:
# memperbaiki nama kolom agar sesuai dengan tipe datanya
dataset_juli.columns = dataset_new_columns
dataset_juni.columns = dataset_new_columns

In [18]:
# cek dataset setelah diperbaiki
dataset_juli

,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,categori
0,2021-07-01,DKI1 (Bunderan HI),55,76,27,14,20,31,76,PM25,SEDANG
1,2021-07-02,DKI1 (Bunderan HI),55,70,33,16,14,30,70,PM25,SEDANG
2,2021-07-03,DKI1 (Bunderan HI),58,81,33,12,19,25,81,PM25,SEDANG
3,2021-07-04,DKI1 (Bunderan HI),68,102,27,11,27,22,102,PM25,TIDAK SEHAT
4,2021-07-05,DKI1 (Bunderan HI),71,106,28,12,34,25,106,PM25,TIDAK SEHAT
...,...,...,...,...,...,...,...,...,...,...,...
150,2021-07-27,DKI5 (Kebon Jeruk) Jakarta Barat,64,110,32,13,29,35,110,PM25,TIDAK SEHAT
151,2021-07-28,DKI5 (Kebon Jeruk) Jakarta Barat,70,130,33,17,28,45,130,PM25,TIDAK SEHAT
152,2021-07-29,DKI5 (Kebon Jeruk) Jakarta Barat,78,140,32,18,29,39,140,PM25,TIDAK SEHAT
153,2021-07-30,DKI5 (Kebon Jeruk) Jakarta Barat,75,121,37,12,50,21,121,PM25,TIDAK SEHAT
154,2021-07-31,DKI5 (Kebon Jeruk) Jakarta Barat,53,80,29,6,34,13,80,PM25,SEDANG

In [19]:
# cek dataset setelah diperbaiki
dataset_juni

,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,categori
0,2021-06-01,DKI1 (Bunderan HI),59,83,22,18,19,35,83,PM25,SEDANG
1,2021-06-02,DKI1 (Bunderan HI),59,84,21,20,24,38,84,PM25,SEDANG
2,2021-06-03,DKI1 (Bunderan HI),54,76,22,20,17,41,76,PM25,SEDANG
3,2021-06-04,DKI1 (Bunderan HI),63,87,20,13,14,30,87,PM25,SEDANG
4,2021-06-05,DKI1 (Bunderan HI),59,79,23,20,19,38,79,PM25,SEDANG
...,...,...,...,...,...,...,...,...,...,...,...
145,2021-06-26,DKI5 (Kebon Jeruk) Jakarta Barat,45,70,39,8,16,22,70,PM25,SEDANG
146,2021-06-27,DKI5 (Kebon Jeruk) Jakarta Barat,68,120,28,22,17,41,120,PM25,TIDAK SEHAT
147,2021-06-28,DKI5 (Kebon Jeruk) Jakarta Barat,59,99,25,17,21,30,99,PM25,SEDANG
148,2021-06-29,DKI5 (Kebon Jeruk) Jakarta Barat,72,128,35,24,21,50,128,PM25,TIDAK SEHAT
149,2021-06-30,DKI5 (Kebon Jeruk) Jakarta Barat,64,106,28,16,14,33,106,PM25,TIDAK SEHAT

In [20]:
# gabungkan kedua dataset juni dan juli
dataset_juni_juli = pd.concat([dataset_juni, dataset_juli])

In [21]:
# cek dataset
dataset_juni_juli

,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,categori
0,2021-06-01,DKI1 (Bunderan HI),59,83,22,18,19,35,83,PM25,SEDANG
1,2021-06-02,DKI1 (Bunderan HI),59,84,21,20,24,38,84,PM25,SEDANG
2,2021-06-03,DKI1 (Bunderan HI),54,76,22,20,17,41,76,PM25,SEDANG
3,2021-06-04,DKI1 (Bunderan HI),63,87,20,13,14,30,87,PM25,SEDANG
4,2021-06-05,DKI1 (Bunderan HI),59,79,23,20,19,38,79,PM25,SEDANG
...,...,...,...,...,...,...,...,...,...,...,...
150,2021-07-27,DKI5 (Kebon Jeruk) Jakarta Barat,64,110,32,13,29,35,110,PM25,TIDAK SEHAT
151,2021-07-28,DKI5 (Kebon Jeruk) Jakarta Barat,70,130,33,17,28,45,130,PM25,TIDAK SEHAT
152,2021-07-29,DKI5 (Kebon Jeruk) Jakarta Barat,78,140,32,18,29,39,140,PM25,TIDAK SEHAT
153,2021-07-30,DKI5 (Kebon Jeruk) Jakarta Barat,75,121,37,12,50,21,121,PM25,TIDAK SEHAT
154,2021-07-31,DKI5 (Kebon Jeruk) Jakarta Barat,53,80,29,6,34,13,80,PM25,SEDANG

In [22]:
# cek kembali tipe datanya
dataset_juni_juli.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 305 entries, 0 to 154
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   305 non-null    object
 1   stasiun   305 non-null    object
 2   pm10      305 non-null    object
 3   pm25      305 non-null    object
 4   so2       305 non-null    object
 5   co        305 non-null    object
 6   o3        305 non-null    object
 7   no2       305 non-null    object
 8   max       305 non-null    int64
 9   critical  304 non-null    object
 10  categori  305 non-null    object
dtypes: int64(1), object(10)
memory usage: 28.6+ KB

In [23]:
# terlihat ada kolom yang telah berubah dan terlihat lebih baik
# namun masih harus di selidiki lebih lanjut

### 3.5. Handing Column "Tanggal"

#### 3.5.1. Convert tipe data tanggal pada dataset juni juli ke datetime

In [24]:
# convert data teks ke datetime
dataset_juni_juli.tanggal = pd.to_datetime(dataset_juni_juli.tanggal)

In [25]:
# cek data tanggal yang telah di convert
sorted(dataset_juni_juli.tanggal.value_counts().index)

[Timestamp('2021-06-01 00:00:00'),
 Timestamp('2021-06-02 00:00:00'),
 Timestamp('2021-06-03 00:00:00'),
 Timestamp('2021-06-04 00:00:00'),
 Timestamp('2021-06-05 00:00:00'),
 Timestamp('2021-06-06 00:00:00'),
 Timestamp('2021-06-07 00:00:00'),
 Timestamp('2021-06-08 00:00:00'),
 Timestamp('2021-06-09 00:00:00'),
 Timestamp('2021-06-10 00:00:00'),
 Timestamp('2021-06-11 00:00:00'),
 Timestamp('2021-06-12 00:00:00'),
 Timestamp('2021-06-13 00:00:00'),
 Timestamp('2021-06-14 00:00:00'),
 Timestamp('2021-06-15 00:00:00'),
 Timestamp('2021-06-16 00:00:00'),
 Timestamp('2021-06-17 00:00:00'),
 Timestamp('2021-06-18 00:00:00'),
 Timestamp('2021-06-19 00:00:00'),
 Timestamp('2021-06-20 00:00:00'),
 Timestamp('2021-06-21 00:00:00'),
 Timestamp('2021-06-22 00:00:00'),
 Timestamp('2021-06-23 00:00:00'),
 Timestamp('2021-06-24 00:00:00'),
 Timestamp('2021-06-25 00:00:00'),
 Timestamp('2021-06-26 00:00:00'),
 Timestamp('2021-06-27 00:00:00'),
 Timestamp('2021-06-28 00:00:00'),
 Timestamp('2021-06-29 00:00:00'),
 Timestamp('2021-06-30 00:00:00'),
 Timestamp('2021-07-01 00:00:00'),
 Timestamp('2021-07-02 00:00:00'),
 Timestamp('2021-07-03 00:00:00'),
 Timestamp('2021-07-04 00:00:00'),
 Timestamp('2021-07-05 00:00:00'),
 Timestamp('2021-07-06 00:00:00'),
 Timestamp('2021-07-07 00:00:00'),
 Timestamp('2021-07-08 00:00:00'),
 Timestamp('2021-07-09 00:00:00'),
 Timestamp('2021-07-10 00:00:00'),
 Timestamp('2021-07-11 00:00:00'),
 Timestamp('2021-07-12 00:00:00'),
 Timestamp('2021-07-13 00:00:00'),
 Timestamp('2021-07-14 00:00:00'),
 Timestamp('2021-07-15 00:00:00'),
 Timestamp('2021-07-16 00:00:00'),
 Timestamp('2021-07-17 00:00:00'),
 Timestamp('2021-07-18 00:00:00'),
 Timestamp('2021-07-19 00:00:00'),
 Timestamp('2021-07-20 00:00:00'),
 Timestamp('2021-07-21 00:00:00'),
 Timestamp('2021-07-22 00:00:00'),
 Timestamp('2021-07-23 00:00:00'),
 Timestamp('2021-07-24 00:00:00'),
 Timestamp('2021-07-25 00:00:00'),
 Timestamp('2021-07-26 00:00:00'),
 Timestamp('2021-07-27 00:00:00'),
 Timestamp('2021-07-28 00:00:00'),
 Timestamp('2021-07-29 00:00:00'),
 Timestamp('2021-07-30 00:00:00'),
 Timestamp('2021-07-31 00:00:00')]

In [26]:
# cek tipe data tanggal yang telah di convert
dataset_juni_juli.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 305 entries, 0 to 154
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   305 non-null    datetime64[ns]
 1   stasiun   305 non-null    object
 2   pm10      305 non-null    object
 3   pm25      305 non-null    object
 4   so2       305 non-null    object
 5   co        305 non-null    object
 6   o3        305 non-null    object
 7   no2       305 non-null    object
 8   max       305 non-null    int64
 9   critical  304 non-null    object
 10  categori  305 non-null    object
dtypes: datetime64[ns](1), int64(1), object(9)
memory usage: 28.6+ KB

#### 3.5.2. Casting kolom tanggal pada dataset utama

In [27]:
# casting tipe data ke datetime
dataset.tanggal = pd.to_datetime(dataset.tanggal)

In [28]:
# cek tipe data untuk kolom tanggal
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1070 entries, 0 to 154
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1070 non-null   datetime64[ns]
 1   stasiun   765 non-null    object
 2   pm10      1070 non-null   object
 3   pm25      1070 non-null   object
 4   so2       1070 non-null   object
 5   co        1070 non-null   object
 6   o3        1070 non-null   object
 7   no2       1070 non-null   object
 8   max       1070 non-null   object
 9   critical  1062 non-null   object
 10  categori  1068 non-null   object
 11  location  305 non-null    object
dtypes: datetime64[ns](1), object(11)
memory usage: 108.7+ KB

#### 3.5.3. Replace data bulan Juni dan Juli di dataset utama

In [29]:
# cek dataset shape
dataset.shape, dataset_juni_juli.shape

((1070, 12), (305, 11))

In [30]:
# set tanggal menjadi index agar gampang untuk dropingnya pada dataset utama
dataset.set_index("tanggal", inplace = True)
dataset_juni_juli.set_index("tanggal", inplace = True)

In [31]:
# drop row untuk bulan juni dan juli pada dataset utama berdasarkan data datetime pada dataset_juni_juli
dataset.drop(index = dataset_juni_juli.index.unique(), inplace = True)

In [32]:
# cek dataset shape
# length dataset utama telah berkurang 305 menjadi 765
dataset.shape, dataset_juni_juli.shape

((765, 11), (305, 10))

In [33]:
# gabung dataset utama dengan dataset bulan juni juli
dataset = pd.concat([dataset, dataset_juni_juli])

In [34]:
# cek dataset shape
# length dataset utama telah kembali menjadi 1070
dataset.shape, dataset_juni_juli.shape

((1070, 11), (305, 10))

In [35]:
# kembalikan tanggal menjadi kolom
dataset.reset_index(inplace = True)

In [36]:
# cek kembali tipe data
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1070 non-null   datetime64[ns]
 1   stasiun   1070 non-null   object
 2   pm10      1070 non-null   object
 3   pm25      1070 non-null   object
 4   so2       1070 non-null   object
 5   co        1070 non-null   object
 6   o3        1070 non-null   object
 7   no2       1070 non-null   object
 8   max       1070 non-null   object
 9   critical  1061 non-null   object
 10  categori  1069 non-null   object
 11  location  0 non-null      object
dtypes: datetime64[ns](1), object(11)
memory usage: 100.4+ KB

In [37]:
# cek dataset
dataset

,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,categori,location
0,2021-09-01,DKI1 (Bunderan HI),63,88,29,15,24,38,88,PM25,SEDANG,NaN
1,2021-09-02,DKI1 (Bunderan HI),60,83,29,11,30,28,83,PM25,SEDANG,NaN
2,2021-09-03,DKI1 (Bunderan HI),60,82,27,11,37,30,82,PM25,SEDANG,NaN
3,2021-09-04,DKI1 (Bunderan HI),58,77,26,10,31,28,77,PM25,SEDANG,NaN
4,2021-09-05,DKI1 (Bunderan HI),63,85,27,11,28,28,85,PM25,SEDANG,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1065,2021-07-27,DKI5 (Kebon Jeruk) Jakarta Barat,64,110,32,13,29,35,110,PM25,TIDAK SEHAT,NaN
1066,2021-07-28,DKI5 (Kebon Jeruk) Jakarta Barat,70,130,33,17,28,45,130,PM25,TIDAK SEHAT,NaN
1067,2021-07-29,DKI5 (Kebon Jeruk) Jakarta Barat,78,140,32,18,29,39,140,PM25,TIDAK SEHAT,NaN
1068,2021-07-30,DKI5 (Kebon Jeruk) Jakarta Barat,75,121,37,12,50,21,121,PM25,TIDAK SEHAT,NaN
1069,2021-07-31,DKI5 (Kebon Jeruk) Jakarta Barat,53,80,29,6,34,13,80,PM25,SEDANG,NaN

In [38]:
# drop kolom categori yang telah tidak dibutuhkan
dataset.drop(columns = "location", inplace = True)

### 3.6. Handling Column "PM10"

In [39]:
# terlihat tidak ada masalah pada kolom pm10
dataset

,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,categori
0,2021-09-01,DKI1 (Bunderan HI),63,88,29,15,24,38,88,PM25,SEDANG
1,2021-09-02,DKI1 (Bunderan HI),60,83,29,11,30,28,83,PM25,SEDANG
2,2021-09-03,DKI1 (Bunderan HI),60,82,27,11,37,30,82,PM25,SEDANG
3,2021-09-04,DKI1 (Bunderan HI),58,77,26,10,31,28,77,PM25,SEDANG
4,2021-09-05,DKI1 (Bunderan HI),63,85,27,11,28,28,85,PM25,SEDANG
...,...,...,...,...,...,...,...,...,...,...,...
1065,2021-07-27,DKI5 (Kebon Jeruk) Jakarta Barat,64,110,32,13,29,35,110,PM25,TIDAK SEHAT
1066,2021-07-28,DKI5 (Kebon Jeruk) Jakarta Barat,70,130,33,17,28,45,130,PM25,TIDAK SEHAT
1067,2021-07-29,DKI5 (Kebon Jeruk) Jakarta Barat,78,140,32,18,29,39,140,PM25,TIDAK SEHAT
1068,2021-07-30,DKI5 (Kebon Jeruk) Jakarta Barat,75,121,37,12,50,21,121,PM25,TIDAK SEHAT
1069,2021-07-31,DKI5 (Kebon Jeruk) Jakarta Barat,53,80,29,6,34,13,80,PM25,SEDANG

In [40]:
# namun kolom pm10 bukanlah bertipe integer
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1070 non-null   datetime64[ns]
 1   stasiun   1070 non-null   object
 2   pm10      1070 non-null   object
 3   pm25      1070 non-null   object
 4   so2       1070 non-null   object
 5   co        1070 non-null   object
 6   o3        1070 non-null   object
 7   no2       1070 non-null   object
 8   max       1070 non-null   object
 9   critical  1061 non-null   object
 10  categori  1069 non-null   object
dtypes: datetime64[ns](1), object(10)
memory usage: 92.1+ KB

In [41]:
# terdapat beberapa data yang sebenarnya numerik namun bertipe teks serta ada beberapa data yang memang benar berupa teks ("---")
dataset.pm10.to_list()

['63',
 '60',
 '60',
 '58',
 '63',
 '68',
 '52',
 '53',
 '45',
 '51',
 '66',
 '61',
 '51',
 '31',
 '54',
 '48',
 '42',
 '50',
 '53',
 '51',
 '55',
 '57',
 '54',
 '57',
 '49',
 '52',
 '51',
 '45',
 '54',
 '63',
 '79',
 '66',
 '66',
 '62',
 '74',
 '66',
 '58',
 '64',
 '68',
 '58',
 '70',
 '66',
 '56',
 '36',
 '69',
 '52',
 '46',
 '56',
 '52',
 '58',
 '61',
 '64',
 '61',
 '57',
 '55',
 '56',
 '53',
 '49',
 '54',
 '71',
 '57',
 '65',
 '56',
 '53',
 '61',
 '73',
 '60',
 '60',
 '48',
 '49',
 '61',
 '55',
 '51',
 '32',
 '53',
 '51',
 '47',
 '55',
 '56',
 '45',
 '54',
 '57',
 '57',
 '55',
 '54',
 '54',
 '48',
 '46',
 '61',
 '67',
 '68',
 '65',
 '62',
 '57',
 '69',
 '62',
 '56',
 '63',
 '52',
 '45',
 '59',
 '63',
 '54',
 '36',
 '60',
 '53',
 '50',
 '57',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '64',
 '62',
 '56',
 '58',
 '57',
 '65',
 '56',
 '51',
 '47',
 '46',
 '60',
 '58',
 '51',
 '26',
 '53',
 '38',
 '35',
 '46',
 '53',
 '45',
 '47',
 '53',
 '53',
 '51',
 '45',
 '48',
 '51',
 '42',
 '56',
 '68',
 '57',
 '67',
 '70',
 '58',
 '55',
 '60',
 '45',
 '54',
 '52',
 '58',
 '59',
 '56',
 '52',
 '64',
 '75',
 '66',
 '65',
 '44',
 '41',
 '33',
 '45',
 '64',
 '57',
 '58',
 '62',
 '55',
 '55',
 '51',
 '50',
 '48',
 '53',
 '57',
 '70',
 '64',
 '62',
 '65',
 '65',
 '49',
 '60',
 '53',
 '60',
 '68',
 '77',
 '57',
 '73',
 '82',
 '64',
 '71',
 '50',
 '46',
 '50',
 '52',
 '73',
 '67',
 '62',
 '65',
 '63',
 '62',
 '51',
 '54',
 '64',
 '56',
 '58',
 '64',
 '54',
 '52',
 '42',
 '48',
 '44',
 '---',
 '45',
 '55',
 '58',
 '47',
 '52',
 '61',
 '72',
 '64',
 '65',
 '51',
 '45',
 '36',
 '53',
 '58',
 '59',
 '68',
 '62',
 '51',
 '45',
 '47',
 '37',
 '48',
 '45',
 '---',
 '---',
 '---',
 '---',
 '---',
 '66',
 '52',
 '58',
 '55',
 '61',
 '62',
 '70',
 '---',
 '---',
 '100',
 '67',
 '---',
 '57',
 '52',
 '---',
 '---',
 '71',
 '65',
 '68',
 '62',
 '75',
 '59',
 '54',
 '51',
 '62',
 '---',
 '55',
 '67',
 '55',
 '53',
 '52',
 '52',
 '50',
 '53',
 '53',
 '55',
 '59',
 '57',
 '47',
 '58',
 '70',
 '68',
 '62',
 '52',
 '50',
 '42',
 '42',
 '60',
 '52',
 '60',
 '64',
 '58',
 '53',
 '51',
 '50',
 '50',
 '49',
 '58',
 '50',
 '49',
 '57',
 '56',
 '55',
 '38',
 '38',
 '55',
 '38',
 '41',
 '32',
 '51',
 '42',
 '27',
 '31',
 '55',
 '55',
 '28',
 '28',
 '41',
 '27',
 '20',
 '23',
 '39',
 '34',
 '30',
 '19',
 '23',
 '29',
 '64',
 '51',
 '52',
 '63',
 '64',
 '51',
 '39',
 '53',
 '61',
 '32',
 '37',
 '34',
 '---',
 '---',
 '---',
 '28',
 '60',
 '58',
 '32',
 '29',
 '40',
 '25',
 '25',
 '21',
 '39',
 '48',
 '34',
 '18',
 '22',
 '30',
 '50',
 '50',
 '40',
 '52',
 '52',
 '55',
 '44',
 '33',
 '67',
 '51',
 '47',
 '44',
 '43',
 '40',
 '29',
 '53',
 '47',
 '55',
 '20',
 '37',
 '52',
 '29',
 '24',
 '35',
 '63',
 '51',
 '31',
 '16',
 '29',
 '46',
 '---',
 '54',
 '51',
 '58',
 '61',
 '55',
 '52',
 '52',
 '64',
 '61',
 '45',
 '32',
 '52',
 '48',
 '36',
 '42',
 '60',
 '63',
 '23',
 '26',
 '44',
 '23',
 '17',
 '27',
 '54',
 '58',
 '37',
 '18',
 '29',
 '39',
 '59',
 '51',
 '44',
 '57',
 '57',
 '57',
 '35',
 '35',
 '57',
 '40',
 '42',
 '37',
 '46',
 '50',
 '19',
 '26',
 '52',
 '52',
 '23',
 '28',
 '46',
 '22',
 '15',
 '22',
 '43',
 '32',
 '22',
 '18',
 '15',
 '23',
 '49',
 '28',
 '49',
 '39',
 '41',
 '60',
 '30',
 '45',
 '33',
 '46',
 '28',
 '44',
 '31',
 '46',
 '58',
 '56',
 '53',
 '51',
 '58',
 '52',
 '52',
 '63',
 '56',
 '34',
 '53',
 '35',
 '52',
 '51',
 '31',
 '55',
 '62',
 '53',
 '32',
 '34',
 '40',
 '46',
 '61',
 '33',
 '49',
 '31',
 '33',
 '33',
 '49',
 '31',
 '51',
 '62',
 '---',
 '58',
 '44',
 '65',
 '53',
 '55',
 '65',
 '70',
 '36',
 '53',
 '41',
 '50',
 '53',
 '28',
 '47',
 '61',
 '53',
 '35',
 '54',
 '50',
 '51',
 '62',
 '20',
 '39',
 '46',
 '51',
 '38',
 '48',
 '53',
 '40',
 '54',
 '47',
 '39',
 '35',
 '57',
 '54',
 '49',
 '56',
 '56',
 '33',
 '54',
 '39',
 '75',
 '51',
 '47',
 '60',
 '64',
 '63',
 '33',
 '41',
 '42',
 '53',
 '52',
 '179',
 '47',
 '38',
 '45',
 '32',
 '---',
 '---',
 '50',
 '69',
 '78',
 '55',
 '---',
 '64',
 '57',
 '62',
 '62',
 '62',
 '34',
 '56',
 '44',
 '68',
 '59',
 '61',
 '60',
 '58',
 '50',
 '22',
 '30',
 '34',
 '51',
 '61',
 '25',
 '44',
 '30',
 '48',
 '32',
 '39',
 '22',
 '36',
 '51',
 '56',
 '52',
 '45',
 '54',
 '48',
 '47',
 '62',
 '59',
 '32',
 '55',
 '32',
 '54',
 '44',
 '34',
 '53',
 '60',
 51,
 47,
 50,
 52,
 52,
 56,
 55,
 53,
 52,
 32,
 55,
 55,
 56,
 65,
 56,
 53,
 56,
 59,
 60,
 58,
 59,
 59,
 56,
 59,
 62,
 56,
 62,
 65,
 65,
 79,
 64,
 55,
 52,
 61,
 64,
 61,
 76,
 63,
 60,
 56,
 36,
 58,
 65,
 58,
 69,
 63,
 60,
 62,
 59,
 72,
 73,
 60,
 71,
 63,
 69,
 69,
 61,
 63,
 76,
 68,
 79,
 74,
 51,
 48,
 45,
 56,
 52,
 52,
 59,
 57,
 53,
 36,
 61,
 54,
 61,
 69,
 57,
 53,
 60,
 58,
 68,
 57,
 53,
 58,
 66,
 66,
 57,
 54,
 62,
 63,
 67,
 87,
 64,
 51,
 42,
 55,
 51,
 53,
 59,
 59,
 54,
 48,
 35,
 56,
 57,
 55,
 58,
 63,
 55,
 59,
 58,
 67,
 64,
 50,
 74,
 63,
 61,
 62,
 53,
 58,
 65,
 66,
 76,
 61,
 44,
 46,
 53,
 46,
 50,
 57,
 50,
 49,
 45,
 26,
 54,
 54,
 61,
 73,
 62,
 51,
 59,
 62,
 63,
 55,
 58,
 62,
 59,
 60,
 63,
 64,
 61,
 63,
 67,
 83,
 60,
 59,
 59,
 54,
 63,
 59,
 59,
 52,
 58,
 58,
 66,
 59,
 57,
 51,
 58,
 62,
 56,
 56,
 64,
 54,
 75,
 52,
 44,
 54,
 65,
 59,
 54,
 65,
 55,
 66,
 65,
 60,
 68,
 68,
 66,
 64,
 61,
 61,
 70,
 68,
 71,
 65,
 67,
 55,
 69,
 69,
 67,
 61,
 77,
 64,
 81,
 62,
 59,
 66,
 80,
 70,
 62,
 67,
 65,
 75,
 79,
 73,
 62,
 58,
 59,
 58,
 63,
 55,
 54,
 59,
 67,
 60,
 53,
 49,
 59,
 73,
 63,
 66,
 62,
 63,
 80,
 53,
 34,
 59,
 69,
 85,
 58,
 72,
 58,
 71,
 79,
 65,
 63,
 54,
 62,
 57,
 56,
 50,
 62,
 68,
 68,
 64,
 55,
 49,
 63,
 67,
 62,
 64,
 67,
 56,
 74,
 51,
 47,
 58,
 66,
 82,
 67,
 72,
 60,
 65,
 65,
 57,
 57,
 53,
 53,
 57,
 54,
 53,
 52,
 52,
 61,
 53,
 49,
 47,
 57,
 56,
 58,
 54,
 62,
 53,
 74,
 50,
 35,
 58,
 64,
 76,
 45,
 68,
 59,
 72,
 64,
 '55',
 '55',
 '58',
 '68',
 '71',
 '56',
 '64',
 '68',
 '70',
 '64',
 '54',
 '46',
 '63',
 '53',
 '66',
 '71',
 '63',
 '63',
 '66',
 '74',
 '48',
 '53',
 '58',
 '53',
 '70',
 '65',
 '61',
 '68',
 '59',
 '73',
 '54',
 '64',
 '68',
 '72',
 '94',
 '77',
 '64',
 '84',
 '83',
 '92',
 '78',
 '---',
 '64',
 '78',
 '56',
 '79',
 '85',
 '74',
 '82',
 '74',
 '86',
 '54',
 '60',
 '61',
 '66',
 '81',
 '79',
 '82',
 '82',
 '69',
 '90',
 '63',
 '64',
 '60',
 '80',
 '86',
 '67',
 '68',
 '73',
 '71',
 '79',
 '67',
 '60',
 '50',
 '62',
 '66',
 '80',
 '84',
 '70',
 '79',
 '80',
 '77',
 '54',
 '57',
 '63',
 ...]

In [42]:
# replace data teks dengan -1
dataset.pm10 = dataset.pm10.replace("---", -1).astype(int)

In [43]:
# cek tipe data
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1070 non-null   datetime64[ns]
 1   stasiun   1070 non-null   object
 2   pm10      1070 non-null   int32
 3   pm25      1070 non-null   object
 4   so2       1070 non-null   object
 5   co        1070 non-null   object
 6   o3        1070 non-null   object
 7   no2       1070 non-null   object
 8   max       1070 non-null   object
 9   critical  1061 non-null   object
 10  categori  1069 non-null   object
dtypes: datetime64[ns](1), int32(1), object(9)
memory usage: 87.9+ KB

### 3.7. Handling Column "PM25"

In [47]:
# cek tipe data
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1070 non-null   datetime64[ns]
 1   stasiun   1070 non-null   object
 2   pm10      1070 non-null   int32
 3   pm25      1070 non-null   object
 4   so2       1070 non-null   object
 5   co        1070 non-null   object
 6   o3        1070 non-null   object
 7   no2       1070 non-null   object
 8   max       1070 non-null   object
 9   critical  1061 non-null   object
 10  categori  1069 non-null   object
dtypes: datetime64[ns](1), int32(1), object(9)
memory usage: 87.9+ KB

In [48]:
# cek janis data
dataset.pm25.to_list()

['88',
 '83',
 '82',
 '77',
 '85',
 '92',
 '65',
 '76',
 '62',
 '66',
 '93',
 '80',
 '64',
 '42',
 '81',
 '65',
 '66',
 '73',
 '78',
 '69',
 '81',
 '80',
 '80',
 '74',
 '67',
 '72',
 '72',
 '63',
 '76',
 '94',
 '102',
 '89',
 '87',
 '79',
 '100',
 '87',
 '72',
 '87',
 '88',
 '77',
 '99',
 '82',
 '71',
 '47',
 '95',
 '66',
 '66',
 '79',
 '73',
 '81',
 '85',
 '82',
 '85',
 '76',
 '81',
 '74',
 '77',
 '71',
 '81',
 '105',
 '83',
 '99',
 '86',
 '77',
 '93',
 '108',
 '84',
 '82',
 '61',
 '71',
 '89',
 '78',
 '65',
 '51',
 '81',
 '72',
 '72',
 '80',
 '81',
 '59',
 '78',
 '78',
 '82',
 '77',
 '75',
 '74',
 '71',
 '---',
 '26',
 '27',
 '118',
 '115',
 '111',
 '93',
 '120',
 '109',
 '86',
 '106',
 '82',
 '80',
 '109',
 '111',
 '88',
 '61',
 '110',
 '89',
 '85',
 '101',
 '---',
 '---',
 '99',
 '119',
 '116',
 '109',
 '102',
 '98',
 '89',
 '69',
 '102',
 '117',
 '95',
 '101',
 '92',
 '84',
 '89',
 '95',
 '77',
 '78',
 '69',
 '73',
 '98',
 '84',
 '70',
 '37',
 '79',
 '59',
 '60',
 '69',
 '83',
 '65',
 '77',
 '78',
 '77',
 '73',
 '64',
 '67',
 '78',
 '64',
 '87',
 '108',
 '81',
 '99',
 '85',
 '82',
 '76',
 '83',
 '62',
 '77',
 '69',
 '83',
 '80',
 '76',
 '67',
 '90',
 '106',
 '95',
 '93',
 '55',
 '58',
 '53',
 '65',
 '95',
 '83',
 '85',
 '95',
 '78',
 '76',
 '69',
 '64',
 '68',
 '70',
 '84',
 '103',
 '86',
 '95',
 '90',
 '91',
 '64',
 '85',
 '77',
 '83',
 '100',
 '105',
 '76',
 '105',
 '108',
 '95',
 '---',
 '60',
 '63',
 '67',
 '68',
 '115',
 '95',
 '96',
 '100',
 '83',
 '86',
 '70',
 '74',
 '90',
 '79',
 '77',
 '100',
 '76',
 '72',
 '65',
 '67',
 '62',
 '---',
 '63',
 '77',
 '79',
 '65',
 '71',
 '88',
 '107',
 '92',
 '95',
 '66',
 '61',
 '52',
 '74',
 '82',
 '87',
 '102',
 '90',
 '71',
 '64',
 '60',
 '31',
 '31',
 '27',
 '91',
 '127',
 '96',
 '110',
 '---',
 '103',
 '77',
 '98',
 '83',
 '97',
 '100',
 '111',
 '91',
 '131',
 '157',
 '122',
 '126',
 '88',
 '80',
 '96',
 '---',
 '120',
 '109',
 '113',
 '104',
 '130',
 '90',
 '78',
 '79',
 '103',
 '79',
 '84',
 '102',
 '82',
 '80',
 '79',
 '74',
 '71',
 '81',
 '74',
 '80',
 '88',
 '81',
 '69',
 '91',
 '107',
 '112',
 '100',
 '73',
 '81',
 '68',
 '70',
 '95',
 '80',
 '93',
 '101',
 '92',
 '76',
 '77',
 '70',
 '74',
 '74',
 '85',
 '63',
 '63',
 '83',
 '75',
 '72',
 '56',
 '55',
 '73',
 '55',
 '55',
 '49',
 '70',
 '53',
 '39',
 '47',
 '71',
 '75',
 '40',
 '44',
 '54',
 '33',
 '30',
 '35',
 '57',
 '56',
 '37',
 '20',
 '28',
 '50',
 '88',
 '70',
 '---',
 '95',
 '84',
 '73',
 '62',
 '73',
 '86',
 '59',
 '58',
 '54',
 '78',
 '59',
 '57',
 '53',
 '80',
 '81',
 '45',
 '50',
 '58',
 '44',
 '55',
 '45',
 '58',
 '68',
 '---',
 '---',
 '---',
 '---',
 '71',
 '63',
 '62',
 '74',
 '71',
 '75',
 '61',
 '52',
 '95',
 '62',
 '61',
 '61',
 '65',
 '56',
 '53',
 '82',
 '66',
 '71',
 '28',
 '53',
 '76',
 '41',
 '30',
 '55',
 '83',
 '71',
 '41',
 '25',
 '30',
 '31',
 '---',
 '77',
 '83',
 '93',
 '95',
 '86',
 '81',
 '70',
 '106',
 '100',
 '71',
 '63',
 '82',
 '68',
 '58',
 '68',
 '99',
 '106',
 '38',
 '58',
 '65',
 '45',
 '37',
 '59',
 '80',
 '78',
 '56',
 '33',
 '55',
 '66',
 '91',
 '72',
 '69',
 '87',
 '87',
 '81',
 '59',
 '61',
 '86',
 '65',
 '62',
 '57',
 '75',
 '63',
 '39',
 '49',
 '77',
 '74',
 '34',
 '50',
 '62',
 '38',
 '34',
 '43',
 '67',
 '59',
 '36',
 '26',
 '34',
 '52',
 '65',
 '34',
 '31',
 '52',
 '57',
 '81',
 '31',
 '60',
 '50',
 '59',
 '43',
 '57',
 '46',
 '61',
 '75',
 '74',
 '71',
 '63',
 '81',
 '63',
 '74',
 '85',
 '77',
 '52',
 '68',
 '53',
 '71',
 '65',
 '49',
 '71',
 '85',
 '---',
 '50',
 '55',
 '63',
 '65',
 '88',
 '58',
 '71',
 '52',
 '54',
 '50',
 '62',
 '53',
 '65',
 '86',
 '---',
 '75',
 '64',
 '96',
 '67',
 '74',
 '94',
 '99',
 '56',
 '70',
 '55',
 '66',
 '68',
 '---',
 '64',
 '85',
 '70',
 '55',
 '67',
 '65',
 '66',
 '91',
 '28',
 '62',
 '60',
 '65',
 '55',
 '63',
 '68',
 '---',
 '80',
 '68',
 '59',
 '58',
 '90',
 '74',
 '72',
 '82',
 '78',
 '53',
 '77',
 '59',
 '116',
 '74',
 '54',
 '53',
 '52',
 '100',
 '56',
 '71',
 '62',
 '80',
 '83',
 '58',
 '76',
 '63',
 '73',
 '60',
 '---',
 '---',
 '76',
 '124',
 '136',
 '81',
 '69',
 '102',
 '86',
 '---',
 '98',
 '99',
 '65',
 '85',
 '71',
 '121',
 '89',
 '98',
 '102',
 '90',
 '71',
 '42',
 '54',
 '54',
 '71',
 '85',
 '44',
 '66',
 '50',
 '63',
 '54',
 '60',
 '45',
 '56',
 '67',
 '82',
 '73',
 '63',
 '84',
 '65',
 '73',
 '90',
 '88',
 '59',
 '81',
 '57',
 '76',
 '68',
 '54',
 '75',
 '87',
 68,
 63,
 68,
 70,
 66,
 73,
 71,
 69,
 60,
 50,
 73,
 70,
 75,
 92,
 72,
 70,
 77,
 78,
 89,
 84,
 80,
 81,
 77,
 87,
 89,
 77,
 89,
 93,
 96,
 112,
 86,
 75,
 69,
 85,
 89,
 79,
 100,
 79,
 78,
 67,
 53,
 83,
 88,
 79,
 94,
 84,
 80,
 84,
 83,
 101,
 97,
 87,
 100,
 86,
 101,
 98,
 84,
 90,
 104,
 97,
 110,
 96,
 66,
 65,
 66,
 82,
 82,
 77,
 84,
 84,
 69,
 54,
 88,
 73,
 91,
 102,
 84,
 79,
 88,
 86,
 104,
 83,
 80,
 88,
 100,
 100,
 81,
 82,
 92,
 94,
 28,
 27,
 27,
 86,
 81,
 104,
 87,
 90,
 105,
 101,
 92,
 82,
 68,
 102,
 104,
 101,
 98,
 114,
 100,
 103,
 97,
 119,
 106,
 85,
 134,
 106,
 110,
 106,
 91,
 105,
 123,
 122,
 140,
 109,
 70,
 75,
 80,
 74,
 78,
 94,
 71,
 73,
 61,
 52,
 92,
 78,
 100,
 116,
 87,
 74,
 89,
 97,
 106,
 81,
 89,
 94,
 88,
 97,
 95,
 96,
 96,
 100,
 111,
 126,
 92,
 '83',
 '84',
 '76',
 '87',
 '79',
 '83',
 '72',
 '80',
 '77',
 '89',
 '77',
 '77',
 '70',
 '82',
 '86',
 '74',
 '80',
 '84',
 '68',
 '109',
 '64',
 '58',
 '79',
 '90',
 '82',
 '66',
 '94',
 '79',
 '94',
 '94',
 '82',
 '92',
 '93',
 '86',
 '84',
 '80',
 '83',
 '99',
 '87',
 '99',
 '90',
 '91',
 '73',
 '91',
 '90',
 '85',
 '84',
 '98',
 '77',
 '108',
 '75',
 '72',
 '91',
 '99',
 '84',
 '79',
 '94',
 '93',
 '102',
 '105',
 '105',
 '81',
 '78',
 '86',
 '87',
 '95',
 '78',
 '82',
 '88',
 '97',
 '86',
 '73',
 '71',
 '88',
 '114',
 '89',
 '99',
 '87',
 '93',
 '111',
 '64',
 '56',
 '89',
 '106',
 '127',
 '80',
 '110',
 '81',
 '30',
 '26',
 '105',
 '100',
 '89',
 '100',
 '93',
 '93',
 '86',
 '103',
 '108',
 '108',
 '99',
 '93',
 '80',
 '103',
 '111',
 '88',
 '102',
 '102',
 '102',
 '140',
 '90',
 '84',
 '107',
 '119',
 '147',
 '118',
 '134',
 '117',
 '124',
 '125',
 '98',
 '92',
 '90',
 '89',
 '---',
 '---',
 '---',
 '91',
 '86',
 '108',
 '87',
 '81',
 '77',
 '98',
 '89',
 '97',
 '90',
 '101',
 '83',
 '123',
 '68',
 '67',
 '103',
 '107',
 '129',
 '70',
 '120',
 '99',
 '128',
 '106',
 '76',
 '70',
 '81',
 '102',
 '106',
 '74',
 '86',
 '94',
 '101',
 '83',
 '71',
 '59',
 '89',
 '69',
 '95',
 '97',
 '80',
 '89',
 '95',
 '100',
 '66',
 '76',
 '80',
 '79',
 '108',
 '95',
 '91',
 '102',
 '85',
 '105',
 '72',
 '81',
 '81',
 '100',
 '129',
 '111',
 '79',
 '108',
 '111',
 '120',
 '104',
 '---',
 '---',
 '119',
 '75',
 '111',
 '115',
 '99',
 '114',
 '100',
 '113',
 '72',
 '82',
 '---',
 '95',
 '112',
 '109',
 '112',
 '113',
 '97',
 '117',
 '---',
 '92',
 '84',
 '124',
 '132',
 '105',
 '102',
 '109',
 '110',
 '119',
 '97',
 '80',
 '---',
 '99',
 '94',
 '126',
 '123',
 '102',
 '121',
 '122',
 '110',
 '81',
 '79',
 '91',
 ...]

In [49]:
# replace data teks ("---") dengan nilai -1
dataset.pm25 = dataset.pm25.replace("---", -1).astype(int)

In [50]:
# cek tipe data
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1070 non-null   datetime64[ns]
 1   stasiun   1070 non-null   object
 2   pm10      1070 non-null   int32
 3   pm25      1070 non-null   int32
 4   so2       1070 non-null   object
 5   co        1070 non-null   object
 6   o3        1070 non-null   object
 7   no2       1070 non-null   object
 8   max       1070 non-null   object
 9   critical  1061 non-null   object
 10  categori  1069 non-null   object
dtypes: datetime64[ns](1), int32(2), object(8)
memory usage: 83.7+ KB

### 3.8. Handling Column "SO2"

In [51]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1070 non-null   datetime64[ns]
 1   stasiun   1070 non-null   object
 2   pm10      1070 non-null   int32
 3   pm25      1070 non-null   int32
 4   so2       1070 non-null   object
 5   co        1070 non-null   object
 6   o3        1070 non-null   object
 7   no2       1070 non-null   object
 8   max       1070 non-null   object
 9   critical  1061 non-null   object
 10  categori  1069 non-null   object
dtypes: datetime64[ns](1), int32(2), object(8)
memory usage: 83.7+ KB

In [52]:
dataset.so2.to_list()

['29',
 '29',
 '27',
 '26',
 '27',
 '31',
 '28',
 '25',
 '25',
 '27',
 '32',
 '26',
 '29',
 '24',
 '29',
 '29',
 '29',
 '29',
 '26',
 '27',
 '28',
 '29',
 '29',
 '34',
 '31',
 '28',
 '27',
 '25',
 '26',
 '27',
 '55',
 '52',
 '51',
 '50',
 '52',
 '51',
 '51',
 '52',
 '54',
 '53',
 '53',
 '51',
 '52',
 '50',
 '54',
 '52',
 '51',
 '53',
 '50',
 '52',
 '52',
 '54',
 '53',
 '53',
 '52',
 '---',
 '---',
 '---',
 '57',
 '63',
 '46',
 '46',
 '45',
 '45',
 '46',
 '48',
 '48',
 '48',
 '46',
 '49',
 '50',
 '47',
 '47',
 '46',
 '50',
 '50',
 '49',
 '50',
 '48',
 '49',
 '50',
 '49',
 '51',
 '52',
 '50',
 '50',
 '49',
 '49',
 '49',
 '49',
 '40',
 '39',
 '42',
 '42',
 '43',
 '42',
 '42',
 '40',
 '41',
 '42',
 '43',
 '41',
 '42',
 '41',
 '42',
 '42',
 '42',
 '43',
 '---',
 '---',
 '44',
 '44',
 '43',
 '46',
 '45',
 '45',
 '42',
 '41',
 '45',
 '45',
 '30',
 '28',
 '7',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '30',
 '32',
 '29',
 '30',
 '29',
 '38',
 '29',
 '33',
 '27',
 '26',
 '29',
 '37',
 '28',
 '33',
 '29',
 '28',
 '34',
 '25',
 '29',
 '29',
 '25',
 '31',
 '29',
 '27',
 '27',
 '29',
 '29',
 '28',
 '31',
 '31',
 '27',
 '59',
 '61',
 '62',
 '60',
 '67',
 '66',
 '60',
 '64',
 '62',
 '61',
 '64',
 '76',
 '63',
 '65',
 '64',
 '63',
 '63',
 '58',
 '60',
 '73',
 '61',
 '82',
 '81',
 '60',
 '62',
 '67',
 '64',
 '67',
 '80',
 '81',
 '63',
 '49',
 '50',
 '50',
 '50',
 '51',
 '51',
 '50',
 '---',
 '51',
 '51',
 '51',
 '51',
 '52',
 '51',
 '52',
 '51',
 '51',
 '50',
 '50',
 '51',
 '53',
 '51',
 '52',
 '51',
 '51',
 '51',
 '52',
 '51',
 '52',
 '51',
 '---',
 '45',
 '46',
 '44',
 '44',
 '---',
 '47',
 '41',
 '45',
 '47',
 '42',
 '43',
 '47',
 '44',
 '44',
 '41',
 '40',
 '39',
 '42',
 '41',
 '45',
 '44',
 '45',
 '45',
 '44',
 '44',
 '45',
 '43',
 '40',
 '41',
 '43',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '32',
 '29',
 '33',
 '30',
 '31',
 '30',
 '27',
 '29',
 '32',
 '28',
 '48',
 '31',
 '36',
 '29',
 '30',
 '31',
 '50',
 '43',
 '31',
 '33',
 '33',
 '32',
 '32',
 '30',
 '34',
 '32',
 '30',
 '29',
 '30',
 '31',
 '77',
 '13',
 '14',
 '20',
 '26',
 '13',
 '7',
 '---',
 '---',
 '---',
 '28',
 '18',
 '---',
 '---',
 '---',
 '5',
 '21',
 '14',
 '5',
 '7',
 '7',
 '8',
 '5',
 '4',
 '7',
 '11',
 '7',
 '3',
 '4',
 '5',
 '51',
 '51',
 '51',
 '52',
 '52',
 '52',
 '51',
 '52',
 '51',
 '51',
 '51',
 '47',
 '47',
 '47',
 '47',
 '47',
 '49',
 '43',
 '41',
 '43',
 '41',
 '42',
 '41',
 '42',
 '42',
 '41',
 '41',
 '41',
 '42',
 '43',
 '---',
 '40',
 '42',
 '43',
 '43',
 '44',
 '44',
 '44',
 '43',
 '37',
 '37',
 '37',
 '38',
 '36',
 '36',
 '36',
 '39',
 '41',
 '36',
 '38',
 '37',
 '37',
 '36',
 '37',
 '38',
 '38',
 '37',
 '37',
 '37',
 '38',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '19',
 '24',
 '13',
 '17',
 '15',
 '15',
 '15',
 '13',
 '19',
 '16',
 '13',
 '12',
 '13',
 '15',
 '33',
 '31',
 '9',
 '35',
 '39',
 '55',
 '34',
 '33',
 '36',
 '43',
 '33',
 '32',
 '34',
 '46',
 '43',
 '39',
 '42',
 '39',
 '38',
 '39',
 '41',
 '56',
 '57',
 '53',
 '56',
 '51',
 '61',
 '53',
 '54',
 '53',
 '52',
 '8',
 '40',
 '41',
 '43',
 '44',
 '51',
 '42',
 '31',
 '32',
 '34',
 '33',
 '40',
 '34',
 '43',
 '44',
 '---',
 '35',
 '35',
 '40',
 '32',
 '40',
 '36',
 '46',
 '35',
 '38',
 '38',
 '35',
 '38',
 '32',
 '38',
 '33',
 '43',
 '42',
 '43',
 '45',
 '43',
 '47',
 '44',
 '45',
 '46',
 '47',
 '45',
 '43',
 '44',
 '44',
 '43',
 '43',
 '43',
 '35',
 '34',
 '34',
 '34',
 '34',
 '34',
 '34',
 '33',
 '33',
 '35',
 '---',
 '21',
 '21',
 '21',
 '39',
 '38',
 '39',
 '39',
 '39',
 '41',
 '39',
 '40',
 '40',
 '42',
 '39',
 '---',
 '---',
 '40',
 '40',
 '41',
 '39',
 '42',
 '41',
 '42',
 '42',
 '27',
 '26',
 '---',
 '15',
 '13',
 '17',
 '38',
 '37',
 '38',
 '36',
 '18',
 '14',
 '16',
 '27',
 '30',
 '36',
 '22',
 '17',
 '20',
 '32',
 '21',
 '16',
 '20',
 '33',
 '32',
 '23',
 '26',
 '18',
 '19',
 '20',
 '20',
 '19',
 '24',
 '25',
 '34',
 '27',
 '36',
 '20',
 '28',
 '25',
 '28',
 25,
 24,
 26,
 29,
 29,
 28,
 31,
 33,
 30,
 25,
 25,
 28,
 28,
 30,
 31,
 30,
 28,
 25,
 31,
 29,
 25,
 28,
 28,
 27,
 26,
 27,
 30,
 26,
 28,
 27,
 27,
 50,
 50,
 53,
 53,
 55,
 58,
 53,
 53,
 52,
 48,
 50,
 52,
 51,
 53,
 53,
 54,
 51,
 51,
 55,
 55,
 51,
 52,
 52,
 52,
 51,
 51,
 52,
 51,
 52,
 52,
 51,
 44,
 47,
 48,
 51,
 51,
 42,
 45,
 47,
 45,
 41,
 44,
 46,
 46,
 45,
 45,
 48,
 45,
 43,
 45,
 46,
 44,
 49,
 46,
 46,
 44,
 46,
 47,
 46,
 46,
 46,
 10,
 39,
 38,
 38,
 41,
 38,
 37,
 38,
 40,
 40,
 38,
 39,
 40,
 40,
 41,
 39,
 41,
 41,
 38,
 42,
 40,
 39,
 43,
 40,
 42,
 42,
 40,
 39,
 38,
 39,
 41,
 41,
 30,
 27,
 30,
 33,
 30,
 31,
 37,
 39,
 39,
 27,
 29,
 32,
 33,
 38,
 33,
 35,
 32,
 28,
 38,
 39,
 32,
 35,
 31,
 31,
 31,
 32,
 34,
 31,
 32,
 35,
 30,
 '22',
 '21',
 '22',
 '20',
 '23',
 '22',
 '24',
 '26',
 '24',
 '23',
 '22',
 '24',
 '23',
 '25',
 '31',
 '39',
 '28',
 '29',
 '26',
 '33',
 '24',
 '27',
 '26',
 '31',
 '36',
 '31',
 '27',
 '24',
 '30',
 '26',
 '50',
 '54',
 '57',
 '46',
 '51',
 '50',
 '52',
 '53',
 '54',
 '56',
 '51',
 '54',
 '52',
 '53',
 '52',
 '66',
 '51',
 '59',
 '59',
 '66',
 '55',
 '54',
 '51',
 '54',
 '58',
 '53',
 '57',
 '53',
 '52',
 '57',
 '43',
 '45',
 '49',
 '48',
 '44',
 '45',
 '47',
 '48',
 '48',
 '48',
 '47',
 '49',
 '49',
 '49',
 '52',
 '51',
 '50',
 '48',
 '50',
 '52',
 '48',
 '50',
 '52',
 '51',
 '51',
 '51',
 '50',
 '50',
 '52',
 '49',
 '41',
 '41',
 '41',
 '43',
 '41',
 '41',
 '41',
 '44',
 '43',
 '37',
 '---',
 '27',
 '36',
 '35',
 '42',
 '35',
 '35',
 '38',
 '31',
 '36',
 '29',
 '33',
 '38',
 '37',
 '39',
 '36',
 '34',
 '36',
 '34',
 '36',
 '27',
 '25',
 '23',
 '29',
 '24',
 '23',
 '25',
 '25',
 '29',
 '24',
 '22',
 '28',
 '25',
 '27',
 '42',
 '28',
 '30',
 '28',
 '34',
 '47',
 '23',
 '28',
 '26',
 '39',
 '35',
 '39',
 '28',
 '25',
 '35',
 '28',
 '27',
 '33',
 '33',
 '27',
 '28',
 '26',
 '34',
 '32',
 '33',
 '35',
 '32',
 '29',
 '33',
 '28',
 '31',
 '30',
 '29',
 '31',
 '26',
 '27',
 '27',
 '31',
 '26',
 '26',
 '25',
 '27',
 '29',
 '31',
 '28',
 '29',
 '26',
 '53',
 '56',
 '54',
 '51',
 '56',
 '51',
 '54',
 '56',
 '59',
 '54',
 '54',
 '52',
 '54',
 '51',
 '62',
 '53',
 '55',
 '55',
 '51',
 '51',
 '52',
 '53',
 '52',
 '54',
 '55',
 '54',
 '56',
 '53',
 '52',
 '54',
 '50',
 '48',
 '47',
 '45',
 '44',
 '46',
 '44',
 '48',
 '50',
 '51',
 '51',
 '47',
 '47',
 '50',
 '45',
 '49',
 '49',
 '49',
 '49',
 '48',
 '45',
 '45',
 '49',
 '46',
 ...]

In [53]:
dataset.so2 = dataset.so2.replace("---", -1).astype(int)

In [54]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1070 non-null   datetime64[ns]
 1   stasiun   1070 non-null   object
 2   pm10      1070 non-null   int32
 3   pm25      1070 non-null   int32
 4   so2       1070 non-null   int32
 5   co        1070 non-null   object
 6   o3        1070 non-null   object
 7   no2       1070 non-null   object
 8   max       1070 non-null   object
 9   critical  1061 non-null   object
 10  categori  1069 non-null   object
dtypes: datetime64[ns](1), int32(3), object(7)
memory usage: 79.5+ KB

### 3.9. Handling Column "CO"

In [55]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1070 non-null   datetime64[ns]
 1   stasiun   1070 non-null   object
 2   pm10      1070 non-null   int32
 3   pm25      1070 non-null   int32
 4   so2       1070 non-null   int32
 5   co        1070 non-null   object
 6   o3        1070 non-null   object
 7   no2       1070 non-null   object
 8   max       1070 non-null   object
 9   critical  1061 non-null   object
 10  categori  1069 non-null   object
dtypes: datetime64[ns](1), int32(3), object(7)
memory usage: 79.5+ KB

In [56]:
dataset.co.to_list()

['15',
 '11',
 '11',
 '10',
 '11',
 '11',
 '9',
 '16',
 '12',
 '10',
 '12',
 '10',
 '8',
 '8',
 '20',
 '9',
 '7',
 '8',
 '8',
 '10',
 '11',
 '11',
 '8',
 '8',
 '7',
 '6',
 '12',
 '9',
 '12',
 '13',
 '14',
 '10',
 '9',
 '9',
 '12',
 '10',
 '9',
 '13',
 '12',
 '9',
 '11',
 '9',
 '9',
 '8',
 '17',
 '8',
 '7',
 '8',
 '8',
 '11',
 '10',
 '10',
 '8',
 '8',
 '8',
 '7',
 '11',
 '8',
 '10',
 '12',
 '13',
 '15',
 '9',
 '9',
 '11',
 '13',
 '11',
 '12',
 '9',
 '9',
 '10',
 '9',
 '8',
 '7',
 '17',
 '10',
 '7',
 '9',
 '10',
 '7',
 '9',
 '14',
 '10',
 '8',
 '11',
 '10',
 '12',
 '10',
 '13',
 '16',
 '16',
 '12',
 '10',
 '9',
 '12',
 '9',
 '8',
 '15',
 '12',
 '8',
 '10',
 '10',
 '7',
 '6',
 '19',
 '7',
 '6',
 '7',
 '---',
 '---',
 '9',
 '10',
 '9',
 '8',
 '7',
 '7',
 '11',
 '6',
 '13',
 '13',
 '12',
 '9',
 '6',
 '6',
 '7',
 '8',
 '6',
 '8',
 '8',
 '6',
 '8',
 '7',
 '6',
 '3',
 '14',
 '4',
 '3',
 '5',
 '7',
 '5',
 '6',
 '7',
 '6',
 '6',
 '4',
 '4',
 '9',
 '5',
 '11',
 '10',
 '11',
 '11',
 '10',
 '11',
 '11',
 '10',
 '9',
 '11',
 '9',
 '9',
 '10',
 '9',
 '8',
 '11',
 '12',
 '15',
 '11',
 '9',
 '14',
 '10',
 '9',
 '18',
 '10',
 '11',
 '14',
 '14',
 '15',
 '16',
 '19',
 '12',
 '11',
 '10',
 '10',
 '11',
 '11',
 '11',
 '9',
 '9',
 '10',
 '9',
 '9',
 '12',
 '12',
 '9',
 '12',
 '13',
 '13',
 '12',
 '9',
 '16',
 '11',
 '9',
 '14',
 '10',
 '12',
 '12',
 '13',
 '10',
 '12',
 '14',
 '13',
 '12',
 '9',
 '12',
 '8',
 '9',
 '7',
 '6',
 '7',
 '---',
 '7',
 '9',
 '10',
 '8',
 '9',
 '12',
 '14',
 '15',
 '15',
 '11',
 '15',
 '10',
 '11',
 '15',
 '13',
 '17',
 '13',
 '13',
 '8',
 '14',
 '17',
 '12',
 '28',
 '10',
 '10',
 '9',
 '11',
 '---',
 '8',
 '7',
 '9',
 '7',
 '9',
 '10',
 '9',
 '8',
 '12',
 '15',
 '14',
 '13',
 '11',
 '18',
 '10',
 '10',
 '13',
 '10',
 '15',
 '11',
 '16',
 '10',
 '11',
 '15',
 '15',
 '---',
 '8',
 '10',
 '8',
 '7',
 '10',
 '6',
 '8',
 '7',
 '7',
 '8',
 '9',
 '12',
 '7',
 '10',
 '11',
 '14',
 '11',
 '11',
 '16',
 '11',
 '7',
 '15',
 '10',
 '12',
 '13',
 '16',
 '11',
 '16',
 '18',
 '12',
 '10',
 '16',
 '14',
 '13',
 '17',
 '19',
 '13',
 '8',
 '18',
 '14',
 '10',
 '12',
 '10',
 '16',
 '11',
 '8',
 '8',
 '13',
 '18',
 '7',
 '7',
 '15',
 '7',
 '7',
 '8',
 '10',
 '12',
 '10',
 '5',
 '7',
 '9',
 '12',
 '14',
 '---',
 '13',
 '14',
 '11',
 '10',
 '14',
 '11',
 '9',
 '11',
 '9',
 '16',
 '13',
 '9',
 '8',
 '11',
 '10',
 '7',
 '8',
 '15',
 '7',
 '7',
 '7',
 '9',
 '11',
 '8',
 '7',
 '8',
 '8',
 '17',
 '16',
 '13',
 '16',
 '17',
 '13',
 '10',
 '17',
 '21',
 '8',
 '12',
 '10',
 '13',
 '11',
 '8',
 '11',
 '9',
 '9',
 '3',
 '6',
 '14',
 '4',
 '3',
 '5',
 '12',
 '17',
 '8',
 '4',
 '7',
 '10',
 '---',
 '18',
 '12',
 '17',
 '16',
 '11',
 '9',
 '14',
 '15',
 '11',
 '10',
 '7',
 '14',
 '13',
 '7',
 '10',
 '10',
 '9',
 '3',
 '6',
 '19',
 '4',
 '3',
 '5',
 '11',
 '14',
 '8',
 '4',
 '8',
 '8',
 '17',
 '14',
 '12',
 '13',
 '23',
 '11',
 '6',
 '20',
 '16',
 '8',
 '8',
 '5',
 '14',
 '12',
 '3',
 '3',
 '10',
 '10',
 '2',
 '4',
 '17',
 '3',
 '2',
 '3',
 '6',
 '7',
 '7',
 '2',
 '3',
 '4',
 '13',
 '7',
 '19',
 '13',
 '15',
 '23',
 '12',
 '17',
 '10',
 '14',
 '8',
 '17',
 '10',
 '15',
 '19',
 '20',
 '18',
 '18',
 '24',
 '13',
 '19',
 '28',
 '18',
 '15',
 '17',
 '11',
 '15',
 '15',
 '10',
 '16',
 '23',
 '12',
 '7',
 '9',
 '8',
 '14',
 '18',
 '11',
 '15',
 '8',
 '9',
 '8',
 '13',
 '9',
 '9',
 '11',
 '---',
 '15',
 '13',
 '21',
 '11',
 '15',
 '21',
 '19',
 '15',
 '19',
 '15',
 '14',
 '16',
 '12',
 '13',
 '23',
 '12',
 '7',
 '9',
 '10',
 '15',
 '17',
 '7',
 '17',
 '11',
 '12',
 '8',
 '13',
 '11',
 '7',
 '16',
 '11',
 '13',
 '10',
 '20',
 '13',
 '14',
 '21',
 '12',
 '9',
 '18',
 '14',
 '23',
 '13',
 '12',
 '15',
 '44',
 '12',
 '5',
 '7',
 '8',
 '17',
 '20',
 '9',
 '14',
 '9',
 '10',
 '7',
 '---',
 '---',
 '7',
 '15',
 '14',
 '13',
 '13',
 '21',
 '10',
 '17',
 '22',
 '13',
 '---',
 '23',
 '14',
 '21',
 '15',
 '15',
 '17',
 '21',
 '8',
 '2',
 '3',
 '5',
 '12',
 '23',
 '5',
 '13',
 '5',
 '8',
 '5',
 '13',
 '3',
 '3',
 '5',
 '11',
 '8',
 '8',
 '18',
 '6',
 '15',
 '24',
 '16',
 '9',
 '17',
 '9',
 '14',
 '11',
 '8',
 '15',
 '19',
 8,
 10,
 11,
 8,
 9,
 15,
 7,
 6,
 6,
 7,
 10,
 8,
 10,
 15,
 8,
 8,
 13,
 11,
 15,
 11,
 13,
 14,
 10,
 12,
 12,
 10,
 11,
 11,
 12,
 17,
 12,
 9,
 10,
 12,
 9,
 9,
 17,
 8,
 9,
 8,
 8,
 10,
 10,
 10,
 11,
 9,
 9,
 9,
 9,
 13,
 12,
 10,
 13,
 9,
 9,
 11,
 9,
 10,
 10,
 10,
 12,
 10,
 9,
 10,
 9,
 8,
 11,
 16,
 10,
 9,
 7,
 6,
 12,
 7,
 11,
 14,
 12,
 9,
 11,
 10,
 14,
 10,
 10,
 14,
 13,
 11,
 10,
 9,
 9,
 10,
 12,
 16,
 19,
 8,
 9,
 12,
 7,
 8,
 16,
 8,
 7,
 6,
 6,
 11,
 8,
 11,
 9,
 11,
 8,
 8,
 9,
 13,
 11,
 8,
 14,
 10,
 11,
 9,
 7,
 10,
 10,
 12,
 16,
 10,
 8,
 8,
 9,
 7,
 9,
 20,
 7,
 7,
 4,
 6,
 11,
 7,
 11,
 14,
 12,
 7,
 8,
 9,
 13,
 8,
 10,
 12,
 9,
 7,
 10,
 9,
 8,
 8,
 10,
 16,
 7,
 '18',
 '20',
 '20',
 '13',
 '20',
 '15',
 '13',
 '16',
 '14',
 '23',
 '15',
 '17',
 '14',
 '13',
 '13',
 '18',
 '25',
 '17',
 '21',
 '25',
 '16',
 '15',
 '17',
 '17',
 '14',
 '10',
 '18',
 '18',
 '15',
 '19',
 '16',
 '16',
 '16',
 '12',
 '16',
 '11',
 '15',
 '14',
 '13',
 '15',
 '12',
 '12',
 '11',
 '12',
 '11',
 '17',
 '20',
 '15',
 '16',
 '18',
 '14',
 '14',
 '13',
 '14',
 '12',
 '9',
 '11',
 '16',
 '12',
 '14',
 '12',
 '8',
 '8',
 '6',
 '8',
 '11',
 '7',
 '7',
 '8',
 '14',
 '9',
 '6',
 '6',
 '7',
 '9',
 '10',
 '14',
 '10',
 '7',
 '7',
 '4',
 '5',
 '9',
 '9',
 '11',
 '5',
 '9',
 '6',
 '8',
 '10',
 '---',
 '---',
 '11',
 '7',
 '11',
 '9',
 '9',
 '---',
 '---',
 '9',
 '9',
 '13',
 '12',
 '13',
 '13',
 '20',
 '28',
 '19',
 '19',
 '22',
 '14',
 '16',
 '14',
 '15',
 '18',
 '10',
 '18',
 '18',
 '13',
 '14',
 '12',
 '15',
 '18',
 '9',
 '15',
 '13',
 '12',
 '12',
 '9',
 '18',
 '10',
 '10',
 '10',
 '13',
 '10',
 '25',
 '17',
 '23',
 '19',
 '26',
 '16',
 '13',
 '14',
 '19',
 '30',
 '8',
 '22',
 '17',
 '24',
 '16',
 '14',
 '16',
 '12',
 '11',
 '12',
 '9',
 '10',
 '10',
 '9',
 '7',
 '6',
 '5',
 '10',
 '10',
 '12',
 '11',
 '8',
 '8',
 '10',
 '15',
 '7',
 '9',
 '9',
 '13',
 '23',
 '14',
 '10',
 '13',
 '13',
 '12',
 '7',
 '12',
 '14',
 '11',
 '15',
 '12',
 '10',
 '11',
 '11',
 '11',
 '10',
 '10',
 '9',
 '11',
 '12',
 '11',
 '11',
 '10',
 '11',
 '10',
 '14',
 '9',
 '11',
 '9',
 '13',
 '16',
 '12',
 '12',
 '13',
 '12',
 '12',
 '8',
 '8',
 '7',
 '10',
 '9',
 '7',
 '7',
 '8',
 '6',
 '7',
 '4',
 '5',
 '4',
 '8',
 '6',
 '9',
 '7',
 '5',
 '5',
 '4',
 '5',
 '4',
 '5',
 '5',
 ...]

In [57]:
dataset.co = dataset.co.replace("---", -1).astype(int)

In [58]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1070 non-null   datetime64[ns]
 1   stasiun   1070 non-null   object
 2   pm10      1070 non-null   int32
 3   pm25      1070 non-null   int32
 4   so2       1070 non-null   int32
 5   co        1070 non-null   int32
 6   o3        1070 non-null   object
 7   no2       1070 non-null   object
 8   max       1070 non-null   object
 9   critical  1061 non-null   object
 10  categori  1069 non-null   object
dtypes: datetime64[ns](1), int32(4), object(6)
memory usage: 75.4+ KB

### 3.10. Handling Column "O3"

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1070 non-null   datetime64[ns]
 1   stasiun   1070 non-null   object
 2   pm10      1070 non-null   int32
 3   pm25      1070 non-null   int32
 4   so2       1070 non-null   object
 5   co        1070 non-null   object
 6   o3        1070 non-null   object
 7   no2       1070 non-null   object
 8   max       1070 non-null   object
 9   critical  1061 non-null   object
 10  categori  1069 non-null   object
dtypes: datetime64[ns](1), int32(2), object(8)
memory usage: 83.7+ KB

In [60]:
dataset.o3.to_list()

['24',
 '30',
 '37',
 '31',
 '28',
 '26',
 '19',
 '23',
 '27',
 '25',
 '34',
 '28',
 '23',
 '20',
 '20',
 '23',
 '26',
 '23',
 '33',
 '25',
 '29',
 '24',
 '27',
 '20',
 '24',
 '28',
 '22',
 '24',
 '29',
 '38',
 '30',
 '39',
 '39',
 '37',
 '35',
 '34',
 '27',
 '27',
 '35',
 '32',
 '46',
 '36',
 '27',
 '47',
 '45',
 '52',
 '53',
 '51',
 '68',
 '54',
 '58',
 '48',
 '53',
 '47',
 '50',
 '54',
 '47',
 '49',
 '63',
 '63',
 '32',
 '29',
 '39',
 '30',
 '36',
 '29',
 '26',
 '29',
 '31',
 '36',
 '43',
 '30',
 '26',
 '21',
 '24',
 '27',
 '29',
 '27',
 '31',
 '33',
 '35',
 '26',
 '29',
 '27',
 '22',
 '27',
 '26',
 '32',
 '31',
 '40',
 '26',
 '26',
 '34',
 '31',
 '27',
 '29',
 '21',
 '29',
 '27',
 '26',
 '33',
 '24',
 '18',
 '19',
 '18',
 '28',
 '29',
 '23',
 '---',
 '---',
 '32',
 '22',
 '24',
 '21',
 '26',
 '33',
 '29',
 '38',
 '38',
 '40',
 '28',
 '25',
 '45',
 '37',
 '36',
 '27',
 '19',
 '28',
 '32',
 '39',
 '45',
 '29',
 '20',
 '17',
 '22',
 '23',
 '25',
 '27',
 '28',
 '30',
 '34',
 '25',
 '27',
 '20',
 '24',
 '30',
 '22',
 '26',
 '34',
 '46',
 '32',
 '30',
 '28',
 '34',
 '30',
 '26',
 '21',
 '24',
 '32',
 '38',
 '35',
 '23',
 '25',
 '35',
 '34',
 '32',
 '36',
 '19',
 '15',
 '21',
 '28',
 '19',
 '20',
 '28',
 '33',
 '23',
 '22',
 '22',
 '18',
 '25',
 '32',
 '65',
 '58',
 '53',
 '64',
 '54',
 '58',
 '50',
 '54',
 '60',
 '72',
 '66',
 '49',
 '58',
 '70',
 '64',
 '63',
 '65',
 '45',
 '42',
 '50',
 '57',
 '46',
 '53',
 '62',
 '70',
 '50',
 '49',
 '49',
 '49',
 '56',
 '56',
 '35',
 '28',
 '32',
 '36',
 '36',
 '34',
 '28',
 '---',
 '38',
 '40',
 '39',
 '37',
 '38',
 '32',
 '40',
 '35',
 '39',
 '24',
 '18',
 '29',
 '29',
 '---',
 '39',
 '47',
 '38',
 '30',
 '33',
 '15',
 '13',
 '39',
 '39',
 '35',
 '35',
 '32',
 '33',
 '---',
 '37',
 '27',
 '30',
 '36',
 '43',
 '44',
 '32',
 '38',
 '45',
 '50',
 '51',
 '53',
 '32',
 '31',
 '33',
 '48',
 '36',
 '35',
 '39',
 '41',
 '36',
 '50',
 '56',
 '45',
 '58',
 '---',
 '34',
 '31',
 '28',
 '31',
 '35',
 '28',
 '25',
 '32',
 '43',
 '46',
 '39',
 '31',
 '30',
 '35',
 '39',
 '32',
 '48',
 '19',
 '13',
 '22',
 '34',
 '24',
 '29',
 '35',
 '36',
 '29',
 '32',
 '29',
 '23',
 '30',
 '31',
 '22',
 '22',
 '21',
 '34',
 '18',
 '22',
 '23',
 '15',
 '17',
 '16',
 '13',
 '16',
 '27',
 '18',
 '16',
 '11',
 '15',
 '19',
 '16',
 '13',
 '16',
 '14',
 '13',
 '12',
 '11',
 '9',
 '8',
 '14',
 '12',
 '18',
 '48',
 '49',
 '41',
 '63',
 '46',
 '52',
 '55',
 '39',
 '47',
 '36',
 '36',
 '38',
 '52',
 '46',
 '36',
 '41',
 '45',
 '56',
 '42',
 '41',
 '45',
 '41',
 '41',
 '37',
 '40',
 '39',
 '45',
 '47',
 '42',
 '44',
 '27',
 '18',
 '37',
 '36',
 '22',
 '42',
 '24',
 '25',
 '---',
 '14',
 '12',
 '30',
 '40',
 '---',
 '---',
 '24',
 '28',
 '---',
 '28',
 '31',
 '29',
 '27',
 '29',
 '34',
 '27',
 '---',
 '---',
 '34',
 '19',
 '35',
 '---',
 '47',
 '73',
 '27',
 '14',
 '26',
 '35',
 '26',
 '31',
 '20',
 '13',
 '19',
 '30',
 '24',
 '16',
 '15',
 '19',
 '27',
 '17',
 '21',
 '13',
 '14',
 '15',
 '26',
 '24',
 '17',
 '13',
 '18',
 '17',
 '24',
 '22',
 '13',
 '21',
 '31',
 '16',
 '24',
 '22',
 '13',
 '19',
 '17',
 '10',
 '15',
 '29',
 '19',
 '14',
 '13',
 '14',
 '20',
 '15',
 '16',
 '14',
 '14',
 '13',
 '13',
 '14',
 '15',
 '18',
 '16',
 '13',
 '21',
 '15',
 '15',
 '7',
 '15',
 '15',
 '18',
 '16',
 '18',
 '21',
 '19',
 '24',
 '15',
 '13',
 '16',
 '20',
 '24',
 '24',
 '22',
 '33',
 '23',
 '22',
 '25',
 '20',
 '17',
 '17',
 '22',
 '20',
 '18',
 '24',
 '23',
 '20',
 '41',
 '40',
 '48',
 '43',
 '39',
 '45',
 '43',
 '51',
 '50',
 '41',
 '51',
 '42',
 '34',
 '35',
 '50',
 '---',
 '57',
 '54',
 '78',
 '58',
 '---',
 '54',
 '42',
 '36',
 '35',
 '37',
 '40',
 '34',
 '37',
 '38',
 '37',
 '32',
 '29',
 '32',
 '26',
 '27',
 '42',
 '32',
 '45',
 '51',
 '---',
 '47',
 '---',
 '23',
 '37',
 '---',
 '---',
 '---',
 '33',
 '48',
 '43',
 '39',
 '44',
 '44',
 '31',
 '31',
 '36',
 '38',
 '17',
 '20',
 '19',
 '17',
 '19',
 '18',
 '23',
 '14',
 '13',
 '23',
 '17',
 '25',
 '28',
 '24',
 '22',
 '---',
 '---',
 '28',
 '29',
 '32',
 '34',
 '24',
 '40',
 '30',
 '13',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '---',
 '19',
 '19',
 '18',
 '14',
 '12',
 '18',
 '15',
 '23',
 '31',
 '28',
 '31',
 '20',
 '16',
 '21',
 '31',
 '34',
 '28',
 '22',
 '35',
 '22',
 '31',
 '29',
 '23',
 '19',
 '15',
 '20',
 '21',
 '21',
 '25',
 '23',
 '30',
 29,
 25,
 19,
 24,
 21,
 11,
 18,
 23,
 25,
 29,
 24,
 20,
 17,
 24,
 17,
 17,
 26,
 27,
 24,
 32,
 26,
 25,
 25,
 32,
 34,
 22,
 25,
 40,
 30,
 39,
 35,
 67,
 59,
 47,
 50,
 58,
 38,
 48,
 57,
 57,
 55,
 59,
 47,
 49,
 53,
 46,
 42,
 40,
 42,
 26,
 34,
 29,
 25,
 33,
 41,
 38,
 26,
 32,
 41,
 30,
 38,
 48,
 31,
 29,
 30,
 27,
 23,
 19,
 23,
 26,
 25,
 27,
 30,
 32,
 29,
 29,
 22,
 24,
 30,
 35,
 27,
 29,
 33,
 29,
 31,
 32,
 33,
 30,
 31,
 42,
 35,
 38,
 38,
 30,
 27,
 21,
 23,
 21,
 13,
 19,
 21,
 26,
 30,
 27,
 21,
 19,
 21,
 15,
 17,
 24,
 30,
 28,
 28,
 25,
 22,
 24,
 26,
 26,
 28,
 28,
 36,
 28,
 30,
 32,
 29,
 27,
 27,
 26,
 17,
 12,
 19,
 23,
 21,
 24,
 25,
 27,
 21,
 26,
 17,
 22,
 26,
 30,
 26,
 34,
 31,
 24,
 22,
 32,
 29,
 31,
 29,
 44,
 36,
 32,
 32,
 '19',
 '24',
 '17',
 '14',
 '19',
 '19',
 '28',
 '24',
 '23',
 '18',
 '23',
 '27',
 '25',
 '22',
 '17',
 '13',
 '17',
 '16',
 '13',
 '21',
 '18',
 '16',
 '24',
 '17',
 '17',
 '21',
 '22',
 '26',
 '20',
 '19',
 '64',
 '76',
 '61',
 '76',
 '65',
 '72',
 '68',
 '72',
 '67',
 '48',
 '61',
 '57',
 '58',
 '58',
 '44',
 '43',
 '44',
 '49',
 '41',
 '44',
 '44',
 '38',
 '51',
 '42',
 '40',
 '53',
 '57',
 '61',
 '51',
 '55',
 '---',
 '---',
 '---',
 '---',
 '23',
 '26',
 '24',
 '34',
 '26',
 '26',
 '30',
 '35',
 '32',
 '23',
 '24',
 '21',
 '21',
 '25',
 '18',
 '24',
 '22',
 '24',
 '29',
 '26',
 '27',
 '25',
 '29',
 '26',
 '25',
 '23',
 '36',
 '36',
 '32',
 '41',
 '36',
 '38',
 '37',
 '30',
 '27',
 '32',
 '35',
 '30',
 '32',
 '28',
 '22',
 '19',
 '20',
 '18',
 '15',
 '20',
 '19',
 '21',
 '23',
 '16',
 '20',
 '26',
 '29',
 '30',
 '27',
 '21',
 '26',
 '27',
 '19',
 '25',
 '21',
 '25',
 '32',
 '27',
 '28',
 '22',
 '29',
 '29',
 '23',
 '18',
 '16',
 '9',
 '16',
 '16',
 '11',
 '20',
 '12',
 '13',
 '23',
 '17',
 '14',
 '16',
 '17',
 '21',
 '21',
 '14',
 '20',
 '14',
 '19',
 '27',
 '34',
 '29',
 '22',
 '26',
 '28',
 '24',
 '21',
 '18',
 '18',
 '17',
 '24',
 '24',
 '28',
 '32',
 '32',
 '24',
 '26',
 '24',
 '27',
 '21',
 '28',
 '17',
 '23',
 '20',
 '24',
 '39',
 '27',
 '48',
 '40',
 '44',
 '50',
 '62',
 '55',
 '51',
 '50',
 '56',
 '63',
 '54',
 '44',
 '43',
 '50',
 '56',
 '53',
 '58',
 '58',
 '77',
 '60',
 '58',
 '54',
 '59',
 '51',
 '54',
 '46',
 '41',
 '40',
 '53',
 '81',
 '65',
 '22',
 '23',
 '28',
 '28',
 '38',
 '32',
 '31',
 '33',
 '34',
 '31',
 '21',
 '14',
 '25',
 '23',
 '28',
 '29',
 '31',
 '33',
 '33',
 '25',
 '19',
 '22',
 '38',
 ...]

In [61]:
dataset.o3 = dataset.o3.replace("---", -1).astype(int)

In [62]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1070 non-null   datetime64[ns]
 1   stasiun   1070 non-null   object
 2   pm10      1070 non-null   int32
 3   pm25      1070 non-null   int32
 4   so2       1070 non-null   int32
 5   co        1070 non-null   int32
 6   o3        1070 non-null   int32
 7   no2       1070 non-null   object
 8   max       1070 non-null   object
 9   critical  1061 non-null   object
 10  categori  1069 non-null   object
dtypes: datetime64[ns](1), int32(5), object(5)
memory usage: 71.2+ KB

### 3.11. Handling Column "NO2"

In [63]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1070 non-null   datetime64[ns]
 1   stasiun   1070 non-null   object
 2   pm10      1070 non-null   int32
 3   pm25      1070 non-null   int32
 4   so2       1070 non-null   int32
 5   co        1070 non-null   int32
 6   o3        1070 non-null   int32
 7   no2       1070 non-null   object
 8   max       1070 non-null   object
 9   critical  1061 non-null   object
 10  categori  1069 non-null   object
dtypes: datetime64[ns](1), int32(5), object(5)
memory usage: 71.2+ KB

In [64]:
dataset.no2.to_list()

['38',
 '28',
 '30',
 '28',
 '28',
 '24',
 '24',
 '34',
 '31',
 '32',
 '41',
 '27',
 '21',
 '19',
 '45',
 '24',
 '20',
 '22',
 '19',
 '34',
 '36',
 '32',
 '22',
 '26',
 '20',
 '19',
 '33',
 '28',
 '38',
 '37',
 '29',
 '19',
 '18',
 '18',
 '22',
 '13',
 '16',
 '31',
 '29',
 '20',
 '22',
 '12',
 '14',
 '15',
 '35',
 '15',
 '9',
 '15',
 '10',
 '25',
 '19',
 '22',
 '13',
 '13',
 '13',
 '6',
 '17',
 '13',
 '16',
 '24',
 '14',
 '16',
 '13',
 '13',
 '14',
 '15',
 '15',
 '15',
 '12',
 '15',
 '16',
 '13',
 '11',
 '11',
 '22',
 '15',
 '13',
 '15',
 '12',
 '10',
 '15',
 '18',
 '16',
 '15',
 '16',
 '13',
 '16',
 '13',
 '22',
 '19',
 '27',
 '25',
 '23',
 '19',
 '26',
 '16',
 '21',
 '25',
 '24',
 '19',
 '30',
 '19',
 '16',
 '15',
 '23',
 '15',
 '14',
 '15',
 '---',
 '---',
 '20',
 '21',
 '18',
 '18',
 '16',
 '12',
 '19',
 '15',
 '24',
 '27',
 '26',
 '18',
 '9',
 '11',
 '11',
 '13',
 '17',
 '15',
 '15',
 '13',
 '16',
 '12',
 '10',
 '8',
 '26',
 '14',
 '12',
 '12',
 '10',
 '10',
 '13',
 '16',
 '14',
 '17',
 '12',
 '9',
 '18',
 '14',
 '19',
 '13',
 '38',
 '35',
 '28',
 '29',
 '33',
 '35',
 '28',
 '35',
 '29',
 '26',
 '30',
 '35',
 '31',
 '35',
 '37',
 '44',
 '30',
 '26',
 '30',
 '27',
 '32',
 '48',
 '36',
 '36',
 '37',
 '43',
 '39',
 '39',
 '35',
 '40',
 '32',
 '16',
 '17',
 '18',
 '24',
 '27',
 '23',
 '20',
 '20',
 '19',
 '12',
 '26',
 '31',
 '18',
 '28',
 '27',
 '28',
 '22',
 '13',
 '29',
 '26',
 '24',
 '38',
 '28',
 '21',
 '27',
 '32',
 '21',
 '30',
 '26',
 '32',
 '28',
 '11',
 '27',
 '14',
 '11',
 '10',
 '11',
 '11',
 '---',
 '11',
 '14',
 '12',
 '11',
 '15',
 '17',
 '19',
 '18',
 '18',
 '15',
 '17',
 '12',
 '15',
 '17',
 '21',
 '18',
 '15',
 '15',
 '13',
 '18',
 '18',
 '18',
 '---',
 '33',
 '19',
 '19',
 '24',
 '---',
 '17',
 '23',
 '22',
 '21',
 '16',
 '26',
 '25',
 '19',
 '32',
 '26',
 '23',
 '27',
 '19',
 '23',
 '17',
 '18',
 '21',
 '20',
 '23',
 '22',
 '24',
 '21',
 '18',
 '15',
 '18',
 '---',
 '12',
 '16',
 '12',
 '10',
 '16',
 '14',
 '17',
 '16',
 '12',
 '11',
 '11',
 '23',
 '13',
 '14',
 '16',
 '17',
 '10',
 '15',
 '35',
 '23',
 '14',
 '26',
 '16',
 '14',
 '14',
 '24',
 '17',
 '27',
 '33',
 '24',
 '13',
 '41',
 '35',
 '38',
 '47',
 '46',
 '40',
 '25',
 '32',
 '38',
 '25',
 '15',
 '9',
 '12',
 '7',
 '7',
 '6',
 '9',
 '13',
 '5',
 '6',
 '6',
 '5',
 '5',
 '6',
 '7',
 '7',
 '5',
 '4',
 '5',
 '7',
 '28',
 '34',
 '27',
 '42',
 '34',
 '26',
 '17',
 '26',
 '28',
 '21',
 '21',
 '19',
 '25',
 '19',
 '17',
 '14',
 '27',
 '24',
 '12',
 '16',
 '18',
 '12',
 '9',
 '12',
 '21',
 '31',
 '15',
 '9',
 '12',
 '17',
 '20',
 '18',
 '18',
 '19',
 '19',
 '20',
 '16',
 '16',
 '24',
 '11',
 '14',
 '12',
 '18',
 '11',
 '10',
 '11',
 '11',
 '18',
 '5',
 '8',
 '13',
 '6',
 '4',
 '7',
 '11',
 '10',
 '13',
 '6',
 '8',
 '11',
 '---',
 '22',
 '17',
 '24',
 '20',
 '29',
 '17',
 '16',
 '19',
 '19',
 '14',
 '14',
 '17',
 '14',
 '11',
 '14',
 '14',
 '18',
 '8',
 '13',
 '14',
 '9',
 '7',
 '12',
 '18',
 '13',
 '12',
 '10',
 '11',
 '15',
 '27',
 '22',
 '24',
 '22',
 '38',
 '20',
 '8',
 '41',
 '30',
 '18',
 '32',
 '15',
 '40',
 '34',
 '10',
 '10',
 '35',
 '35',
 '7',
 '17',
 '44',
 '10',
 '6',
 '8',
 '16',
 '20',
 '22',
 '8',
 '9',
 '10',
 '12',
 '5',
 '49',
 '9',
 '9',
 '11',
 '9',
 '10',
 '11',
 '12',
 '9',
 '7',
 '6',
 '10',
 '14',
 '16',
 '15',
 '10',
 '15',
 '11',
 '17',
 '19',
 '18',
 '11',
 '9',
 '10',
 '15',
 '13',
 '11',
 '14',
 '14',
 '30',
 '14',
 '17',
 '16',
 '24',
 '31',
 '19',
 '30',
 '20',
 '24',
 '22',
 '22',
 '23',
 '26',
 '30',
 '---',
 '32',
 '24',
 '33',
 '20',
 '33',
 '49',
 '42',
 '27',
 '30',
 '24',
 '24',
 '33',
 '29',
 '35',
 '44',
 '15',
 '9',
 '11',
 '13',
 '12',
 '18',
 '10',
 '13',
 '16',
 '15',
 '12',
 '13',
 '10',
 '11',
 '16',
 '15',
 '16',
 '12',
 '23',
 '15',
 '18',
 '24',
 '17',
 '10',
 '13',
 '12',
 '21',
 '18',
 '9',
 '13',
 '---',
 '23',
 '13',
 '15',
 '15',
 '15',
 '19',
 '15',
 '14',
 '19',
 '19',
 '17',
 '---',
 '---',
 '14',
 '23',
 '18',
 '17',
 '17',
 '22',
 '16',
 '27',
 '34',
 '26',
 '---',
 '---',
 '8',
 '12',
 '22',
 '19',
 '21',
 '22',
 '18',
 '5',
 '9',
 '15',
 '29',
 '57',
 '21',
 '30',
 '15',
 '30',
 '15',
 '34',
 '14',
 '21',
 '28',
 '36',
 '35',
 '32',
 '45',
 '16',
 '49',
 '65',
 '44',
 '52',
 '62',
 '34',
 '47',
 '33',
 '29',
 '44',
 '53',
 22,
 28,
 35,
 26,
 27,
 28,
 18,
 16,
 15,
 16,
 25,
 19,
 28,
 36,
 20,
 19,
 22,
 26,
 35,
 34,
 35,
 28,
 27,
 30,
 34,
 33,
 31,
 27,
 29,
 41,
 33,
 13,
 16,
 25,
 14,
 18,
 31,
 16,
 12,
 10,
 9,
 17,
 18,
 19,
 21,
 16,
 17,
 14,
 17,
 36,
 30,
 21,
 26,
 13,
 18,
 24,
 18,
 21,
 22,
 16,
 29,
 19,
 11,
 12,
 13,
 14,
 15,
 18,
 14,
 13,
 10,
 12,
 14,
 11,
 16,
 16,
 15,
 15,
 13,
 11,
 14,
 14,
 15,
 18,
 17,
 15,
 11,
 15,
 13,
 17,
 15,
 17,
 32,
 22,
 20,
 25,
 20,
 19,
 21,
 18,
 17,
 16,
 19,
 23,
 20,
 25,
 21,
 21,
 21,
 20,
 20,
 28,
 23,
 21,
 29,
 20,
 24,
 28,
 19,
 22,
 23,
 25,
 31,
 26,
 11,
 12,
 21,
 18,
 21,
 52,
 18,
 13,
 14,
 14,
 25,
 18,
 32,
 40,
 30,
 20,
 19,
 17,
 33,
 27,
 24,
 29,
 22,
 12,
 20,
 14,
 15,
 12,
 13,
 29,
 14,
 35,
 38,
 41,
 30,
 38,
 32,
 31,
 38,
 34,
 47,
 40,
 35,
 25,
 26,
 29,
 35,
 39,
 34,
 45,
 44,
 31,
 32,
 43,
 39,
 32,
 23,
 32,
 38,
 28,
 38,
 26,
 28,
 32,
 13,
 25,
 14,
 24,
 23,
 22,
 32,
 25,
 25,
 17,
 20,
 16,
 28,
 33,
 27,
 43,
 35,
 28,
 27,
 28,
 28,
 23,
 17,
 18,
 28,
 18,
 28,
 22,
 17,
 16,
 15,
 15,
 19,
 14,
 15,
 16,
 22,
 17,
 13,
 12,
 15,
 21,
 17,
 19,
 21,
 22,
 29,
 17,
 15,
 23,
 19,
 22,
 15,
 15,
 14,
 19,
 19,
 30,
 21,
 20,
 17,
 23,
 20,
 21,
 29,
 28,
 28,
 26,
 24,
 23,
 21,
 25,
 22,
 28,
 24,
 31,
 26,
 21,
 22,
 25,
 27,
 24,
 18,
 22,
 22,
 21,
 29,
 22,
 27,
 36,
 19,
 29,
 22,
 21,
 28,
 19,
 34,
 25,
 26,
 20,
 25,
 27,
 55,
 41,
 45,
 45,
 58,
 35,
 35,
 28,
 52,
 63,
 22,
 41,
 30,
 50,
 33,
 '31',
 '30',
 '25',
 '22',
 '25',
 '29',
 '27',
 '26',
 '25',
 '23',
 '15',
 '13',
 '24',
 '23',
 '30',
 '29',
 '20',
 '19',
 '28',
 '24',
 '17',
 '26',
 '28',
 '34',
 '38',
 '32',
 '28',
 '30',
 '32',
 '35',
 '24',
 '28',
 '27',
 '23',
 '23',
 '20',
 '17',
 '23',
 '24',
 '26',
 '17',
 '13',
 '13',
 '23',
 '23',
 '26',
 '19',
 '20',
 '17',
 '13',
 '19',
 '13',
 '22',
 '20',
 '30',
 '28',
 '22',
 '27',
 '28',
 '24',
 '29',
 '18',
 '18',
 '18',
 '17',
 '14',
 '15',
 '16',
 '17',
 '16',
 '17',
 '14',
 '14',
 '11',
 '18',
 '15',
 '23',
 '16',
 '14',
 '16',
 '17',
 '18',
 '13',
 '20',
 '16',
 ...]

In [65]:
dataset.no2 = dataset.no2.replace("---", -1).astype(int)

In [66]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1070 non-null   datetime64[ns]
 1   stasiun   1070 non-null   object
 2   pm10      1070 non-null   int32
 3   pm25      1070 non-null   int32
 4   so2       1070 non-null   int32
 5   co        1070 non-null   int32
 6   o3        1070 non-null   int32
 7   no2       1070 non-null   int32
 8   max       1070 non-null   object
 9   critical  1061 non-null   object
 10  categori  1069 non-null   object
dtypes: datetime64[ns](1), int32(6), object(4)
memory usage: 67.0+ KB

### 3.12. Handling Column "Max"

In [67]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1070 non-null   datetime64[ns]
 1   stasiun   1070 non-null   object
 2   pm10      1070 non-null   int32
 3   pm25      1070 non-null   int32
 4   so2       1070 non-null   int32
 5   co        1070 non-null   int32
 6   o3        1070 non-null   int32
 7   no2       1070 non-null   int32
 8   max       1070 non-null   object
 9   critical  1061 non-null   object
 10  categori  1069 non-null   object
dtypes: datetime64[ns](1), int32(6), object(4)
memory usage: 67.0+ KB

In [69]:
dataset["max"].to_list()

[88,
 83,
 82,
 77,
 85,
 92,
 65,
 76,
 62,
 66,
 93,
 80,
 64,
 42,
 81,
 65,
 66,
 73,
 78,
 69,
 81,
 80,
 80,
 74,
 67,
 72,
 72,
 63,
 76,
 94,
 102,
 89,
 87,
 79,
 100,
 87,
 72,
 87,
 88,
 77,
 99,
 82,
 71,
 50,
 95,
 66,
 66,
 79,
 73,
 81,
 85,
 82,
 85,
 76,
 81,
 74,
 77,
 71,
 81,
 105,
 83,
 99,
 86,
 77,
 93,
 108,
 84,
 82,
 61,
 71,
 89,
 78,
 65,
 51,
 81,
 72,
 72,
 80,
 81,
 59,
 78,
 78,
 82,
 77,
 75,
 74,
 71,
 49,
 61,
 67,
 118,
 115,
 111,
 93,
 120,
 109,
 86,
 106,
 82,
 80,
 109,
 111,
 88,
 61,
 110,
 89,
 85,
 101,
 0,
 0,
 99,
 119,
 116,
 109,
 102,
 98,
 89,
 69,
 102,
 117,
 95,
 101,
 92,
 84,
 89,
 95,
 77,
 78,
 69,
 73,
 98,
 84,
 70,
 37,
 79,
 59,
 60,
 69,
 83,
 65,
 77,
 78,
 77,
 73,
 64,
 67,
 78,
 64,
 87,
 108,
 81,
 99,
 85,
 82,
 76,
 83,
 62,
 77,
 69,
 83,
 80,
 76,
 67,
 90,
 106,
 95,
 93,
 55,
 58,
 53,
 65,
 95,
 83,
 85,
 95,
 78,
 76,
 69,
 64,
 68,
 70,
 84,
 103,
 86,
 95,
 90,
 91,
 64,
 85,
 77,
 83,
 100,
 105,
 76,
 105,
 108,
 95,
 71,
 60,
 63,
 73,
 68,
 115,
 95,
 96,
 100,
 83,
 86,
 70,
 80,
 90,
 79,
 77,
 100,
 76,
 72,
 65,
 67,
 62,
 0,
 63,
 77,
 79,
 65,
 71,
 88,
 107,
 92,
 95,
 66,
 61,
 52,
 74,
 82,
 87,
 102,
 90,
 71,
 64,
 60,
 52,
 51,
 45,
 91,
 127,
 96,
 110,
 0,
 103,
 77,
 98,
 83,
 97,
 100,
 111,
 91,
 131,
 157,
 122,
 126,
 88,
 80,
 96,
 48,
 120,
 109,
 113,
 104,
 130,
 90,
 78,
 79,
 103,
 79,
 84,
 102,
 82,
 80,
 79,
 74,
 71,
 81,
 74,
 80,
 88,
 81,
 69,
 91,
 107,
 112,
 100,
 73,
 81,
 68,
 70,
 95,
 80,
 93,
 101,
 92,
 76,
 77,
 70,
 74,
 74,
 85,
 63,
 63,
 83,
 75,
 72,
 56,
 55,
 73,
 55,
 55,
 49,
 70,
 53,
 39,
 47,
 71,
 75,
 40,
 44,
 54,
 33,
 32,
 35,
 57,
 56,
 37,
 29,
 30,
 50,
 88,
 70,
 52,
 95,
 84,
 73,
 62,
 73,
 86,
 59,
 58,
 54,
 78,
 59,
 57,
 53,
 80,
 81,
 45,
 50,
 58,
 44,
 55,
 45,
 58,
 68,
 45,
 47,
 42,
 44,
 71,
 63,
 62,
 74,
 71,
 75,
 61,
 52,
 95,
 62,
 61,
 61,
 65,
 56,
 53,
 82,
 66,
 71,
 41,
 53,
 76,
 42,
 41,
 55,
 83,
 71,
 41,
 41,
 42,
 46,
 0,
 77,
 83,
 93,
 95,
 86,
 81,
 70,
 106,
 100,
 71,
 63,
 82,
 68,
 58,
 68,
 99,
 106,
 38,
 58,
 65,
 45,
 37,
 59,
 80,
 78,
 56,
 37,
 55,
 66,
 91,
 72,
 69,
 87,
 87,
 81,
 59,
 61,
 86,
 65,
 62,
 57,
 75,
 63,
 39,
 49,
 77,
 74,
 34,
 50,
 62,
 38,
 34,
 43,
 67,
 59,
 36,
 26,
 34,
 52,
 '65',
 '34',
 'PM25',
 '52',
 '57',
 '81',
 '34',
 '60',
 '50',
 '59',
 '43',
 '57',
 '46',
 '61',
 '75',
 '74',
 '71',
 '63',
 '81',
 '63',
 '74',
 '85',
 '77',
 '53',
 '68',
 '53',
 '71',
 '65',
 '54',
 '71',
 '85',
 '53',
 '50',
 '55',
 '63',
 '65',
 '88',
 '58',
 '71',
 '52',
 '54',
 '51',
 '62',
 '53',
 '65',
 '86',
 '0',
 '75',
 '64',
 '96',
 '67',
 '74',
 '94',
 '99',
 '56',
 '70',
 '55',
 '66',
 '68',
 '37',
 '64',
 '85',
 '70',
 '55',
 '67',
 '65',
 '66',
 '91',
 '44',
 '62',
 '60',
 '65',
 '55',
 '63',
 '68',
 '44',
 '80',
 '68',
 '59',
 '58',
 '90',
 '74',
 '72',
 '82',
 '78',
 '53',
 '77',
 '59',
 '116',
 '74',
 '54',
 '60',
 '64',
 '100',
 '56',
 '71',
 '62',
 '80',
 '83',
 '179',
 '76',
 '63',
 '73',
 '60',
 '0',
 '0',
 '76',
 '124',
 '136',
 '81',
 '69',
 '102',
 '86',
 '62',
 '98',
 '99',
 '65',
 '85',
 '71',
 '121',
 '89',
 '98',
 '102',
 '90',
 '71',
 '42',
 '54',
 '54',
 '71',
 '85',
 '44',
 '66',
 '50',
 '63',
 '54',
 '60',
 '45',
 '56',
 '67',
 '82',
 '73',
 '63',
 '84',
 '65',
 '73',
 '90',
 '88',
 '59',
 '81',
 '57',
 '76',
 '68',
 '54',
 '75',
 '87',
 68,
 63,
 68,
 70,
 66,
 73,
 71,
 69,
 60,
 50,
 73,
 70,
 75,
 92,
 72,
 70,
 77,
 78,
 89,
 84,
 80,
 81,
 77,
 87,
 89,
 77,
 89,
 93,
 96,
 112,
 86,
 75,
 69,
 85,
 89,
 79,
 100,
 79,
 78,
 67,
 55,
 83,
 88,
 79,
 94,
 84,
 80,
 84,
 83,
 101,
 97,
 87,
 100,
 86,
 101,
 98,
 84,
 90,
 104,
 97,
 110,
 96,
 66,
 65,
 66,
 82,
 82,
 77,
 84,
 84,
 69,
 54,
 88,
 73,
 91,
 102,
 84,
 79,
 88,
 86,
 104,
 83,
 80,
 88,
 100,
 100,
 81,
 82,
 92,
 94,
 67,
 87,
 64,
 86,
 81,
 104,
 87,
 90,
 105,
 101,
 92,
 82,
 68,
 102,
 104,
 101,
 98,
 114,
 100,
 103,
 97,
 119,
 106,
 85,
 134,
 106,
 110,
 106,
 91,
 105,
 123,
 122,
 140,
 109,
 70,
 75,
 80,
 74,
 78,
 94,
 71,
 73,
 61,
 52,
 92,
 78,
 100,
 116,
 87,
 74,
 89,
 97,
 106,
 81,
 89,
 94,
 88,
 97,
 95,
 96,
 96,
 100,
 111,
 126,
 92,
 83,
 84,
 76,
 87,
 79,
 83,
 72,
 80,
 77,
 89,
 77,
 77,
 70,
 82,
 86,
 74,
 80,
 84,
 68,
 109,
 64,
 58,
 79,
 90,
 82,
 66,
 94,
 79,
 94,
 94,
 82,
 92,
 93,
 86,
 84,
 80,
 83,
 99,
 87,
 99,
 90,
 91,
 73,
 91,
 90,
 85,
 84,
 98,
 77,
 108,
 75,
 72,
 91,
 99,
 84,
 79,
 94,
 93,
 102,
 105,
 105,
 81,
 78,
 86,
 87,
 95,
 78,
 82,
 88,
 97,
 86,
 73,
 71,
 88,
 114,
 89,
 99,
 87,
 93,
 111,
 64,
 56,
 89,
 106,
 127,
 80,
 110,
 81,
 71,
 79,
 105,
 100,
 89,
 100,
 93,
 93,
 86,
 103,
 108,
 108,
 99,
 93,
 80,
 103,
 111,
 88,
 102,
 102,
 102,
 140,
 90,
 84,
 107,
 119,
 147,
 118,
 134,
 117,
 124,
 125,
 98,
 92,
 90,
 89,
 57,
 54,
 53,
 91,
 86,
 108,
 87,
 81,
 77,
 98,
 89,
 97,
 90,
 101,
 83,
 123,
 68,
 67,
 103,
 107,
 129,
 70,
 120,
 99,
 128,
 106,
 76,
 70,
 81,
 102,
 106,
 74,
 86,
 94,
 101,
 83,
 71,
 59,
 89,
 69,
 95,
 97,
 80,
 89,
 95,
 100,
 66,
 76,
 80,
 79,
 108,
 95,
 91,
 102,
 85,
 105,
 72,
 81,
 81,
 100,
 129,
 111,
 79,
 108,
 111,
 120,
 104,
 54,
 64,
 119,
 75,
 111,
 115,
 99,
 114,
 100,
 113,
 72,
 82,
 61,
 95,
 112,
 109,
 112,
 113,
 97,
 117,
 65,
 92,
 84,
 124,
 132,
 105,
 102,
 109,
 110,
 119,
 97,
 80,
 50,
 99,
 94,
 126,
 123,
 102,
 121,
 122,
 110,
 81,
 79,
 91,
 ...]

In [73]:
dataset["max"] = dataset["max"].replace("PM25", -1).astype(int)

In [74]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1070 non-null   datetime64[ns]
 1   stasiun   1070 non-null   object
 2   pm10      1070 non-null   int32
 3   pm25      1070 non-null   int32
 4   so2       1070 non-null   int32
 5   co        1070 non-null   int32
 6   o3        1070 non-null   int32
 7   no2       1070 non-null   int32
 8   max       1070 non-null   int32
 9   critical  1061 non-null   object
 10  categori  1069 non-null   object
dtypes: datetime64[ns](1), int32(7), object(3)
memory usage: 62.8+ KB

### 3.13. Handling Column "Critical"

In [77]:
dataset.critical.value_counts()

PM25    1005
PM10      25
SO2       21
O3         9
BAIK       1
Name: critical, dtype: int64

In [78]:
dataset[dataset.critical == "BAIK"]

,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,categori
457,2021-12-03,DKI1 (Bunderan HI),49,31,9,19,7,49,-1,BAIK,NaN

In [86]:
dataset.drop(index = 457, inplace = True)

In [87]:
dataset.loc[457]

KeyError: 457

### 3.14. Handling Column "Categori"

In [89]:
dataset.categori.value_counts()

SEDANG            791
TIDAK SEHAT       207
BAIK               62
TIDAK ADA DATA      9
Name: categori, dtype: int64

In [93]:
dataset.drop(index = dataset[dataset.categori == "TIDAK ADA DATA"].index, inplace = True)

In [94]:
dataset.categori.value_counts()

SEDANG         791
TIDAK SEHAT    207
BAIK            62
Name: categori, dtype: int64

In [96]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1060 entries, 0 to 1069
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1060 non-null   datetime64[ns]
 1   stasiun   1060 non-null   object
 2   pm10      1060 non-null   int32
 3   pm25      1060 non-null   int32
 4   so2       1060 non-null   int32
 5   co        1060 non-null   int32
 6   o3        1060 non-null   int32
 7   no2       1060 non-null   int32
 8   max       1060 non-null   int32
 9   critical  1060 non-null   object
 10  categori  1060 non-null   object
dtypes: datetime64[ns](1), int32(7), object(3)
memory usage: 70.4+ KB

In [97]:
joblib.dump(dataset, "../data/processed/dataset_clean.pkl")

['../data/processed/dataset_clean.pkl']

## 4. Data Defense

In [220]:
def check_data(input_data, params):
    # check data types
    assert input_data.select_dtypes("datetime").columns.to_list() == params["datetime_columns"], "an error occurs in datetime column(s)."
    assert input_data.select_dtypes("object").columns.to_list() == params["object_columns"], "an error occurs in object column(s)."
    assert input_data.select_dtypes("int32").columns.to_list() == params["int32_columns"], "an error occurs in int32 column(s)."

    # check range of data
    assert set(input_data.stasiun).issubset(set(params["range_stasiun"])), "an error occurs in stasiun range."
    assert input_data.pm10.between(params["range_pm10"][0], params["range_pm10"][1]).sum() == len(input_data), "an error occurs in pm10 range."
    assert input_data.pm25.between(params["range_pm25"][0], params["range_pm25"][1]).sum() == len(input_data), "an error occurs in pm25 range."
    assert input_data.so2.between(params["range_so2"][0], params["range_so2"][1]).sum() == len(input_data), "an error occurs in so2 range."
    assert input_data.co.between(params["range_co"][0], params["range_co"][1]).sum() == len(input_data), "an error occurs in co range."
    assert input_data.o3.between(params["range_o3"][0], params["range_o3"][1]).sum() == len(input_data), "an error occurs in o3 range."
    assert input_data.no2.between(params["range_no2"][0], params["range_no2"][1]).sum() == len(input_data), "an error occurs in no2 range."

In [245]:
check_data(dataset, params)

## 5. Data Splitting

In [249]:
x = dataset[params["predictors"]].copy()
y = dataset.categori.copy()

In [266]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.4, random_state = 42, stratify = y)

In [269]:
x_valid, x_test, y_valid, y_test = train_test_split(x_test, y_test, test_size = 0.5, random_state = 42, stratify = y_test)

In [271]:
joblib.dump(x_train, "../data/processed/x_train.pkl")
joblib.dump(y_train, "../data/processed/y_train.pkl")
joblib.dump(x_valid, "../data/processed/x_valid.pkl")
joblib.dump(y_valid, "../data/processed/y_valid.pkl")
joblib.dump(x_test, "../data/processed/x_test.pkl")
joblib.dump(y_test, "../data/processed/y_test.pkl")

['../data/processed/y_test.pkl']